/**
 * Hazardous Materials Awareness — Examination I-3
 *
 * Source: PTS Publications exam prep, Seventh Edition 2022, printed pages
 * 37–48. Answers and citations come from the Examination I-3 key in
 * Appendix A (printed pages 139–148), matched by question number.
 * Answers are source-provided and have not been independently verified.
 *
 * Source discrepancy: the I-3 directions say "There should be 100 exam
 * items", but the exam ends at question 75 and the key has 75 entries.
 */
(function () {
  "use strict";

  var bank = globalThis.ExamPrepBank.createExam({
    examId: "awareness-i3",
    examLabel: "Hazardous Materials Awareness — Examination I-3",
    shortLabel: "Examination I-3",
    level: "awareness",
    idPrefix: "exam-i3"
  });
  var rec = bank.rec;
  var U = { t: "page unreadable.", x: true };
  var BLANK = "A fill-in blank was restored where the OCR dropped the printed underline.";
  var FIG237 = "pages 76, 78, 83. Fig. 2.37, Fig. 2.40, Table 2.5.";

  function blankIssue(excerpt) {
    return { summary: "The printed fill-in blank was dropped by the OCR.", excerpt: excerpt, correction: "Confirm the blank position against the printed page." };
  }

  var questions = [
    rec({ n: 1, key: "1. 4.2.1 RECOGNIZE & ID 1",
      q: "Substances or materials in quantities or forms that may pose an unreasonable risk to health, safety, or property when transported, stored, or used in commerce is a:",
      c: ["hazard class.", "hazardous chemical.", "hazardous material.", "hazardous substance."], a: "C",
      notes: ["The key prints this entry's number as \"4,\"; it is the first Examination I-3 key entry and is matched to question 1."],
      r: ["3.3.28, 4.2.1(1).", "page 9.", "page 25."],
      o: "1. Substances or materials in quantities or forms that may pose an unreasonable risk to health, safety, or property when transported, stored, or used in commerce is a: A. hazard class. B. hazardous chemical. C. hazardous material. D. hazardous substance." }),
    rec({ n: 2, key: "2. 4.2.1 RECOGNIZE & ID 4",
      q: "Federal law requires that local establishments keep a Safety Data Sheet on file when:",
      c: ["at a multi-use building.", "personnel have not received specialized hazmat training.", "hazardous materials are used or stored.", "backup emergency power is not available."], a: "C",
      r: ["4.2.1 (A-1, 11) (B-3), 5.2.1 (A-5) (B-5).", "page 98.", "page 25."],
      o: "2. Federal law requires that local establishments keep a Safety Data Sheet on file when: A. at a multi-use building. B. personnel have not received specialized hazmat training. C. hazardous materials are used or stored. D. backup emergency power is not available." }),
    rec({ n: 3, key: "3. 4.2.1 RECOGNIZE & ID 5",
      q: "The four-digit number appearing on a placard or an orange panel of a tank car is the:",
      c: ["United Nations product identification number.", "capacity of the tank car.", "last date the tank car was pressure tested.", "tank car registration number."], a: "A",
      notes: ["Question 4's choices are printed in a second column beside this question's choices in the scan; this question's lettered choices are legible."],
      r: ["4.2.1 (A-4) (B-5).", "page 73.", "page 35."],
      o: "3. The four-digit number appearing on a placard or an orange panel of a tank car : is the: . A. United Nations product identification number. highway truck. B. capacity of the tank car. railway. C. Jast date the tank car was pressure tested. water. D. tank car registration number." }),
    rec({ n: 4, key: "4. 4.2.1 RECOGNIZE & ID 9",
      q: "A bill of lading contains valuable information about the origin of the product and is the type of shipping paper used when transporting a product of:",
      c: ["highway truck.", "railway.", "water.", "air."], a: null, hold: true,
      issues: [{ summary: "The choices are printed as an unlabeled column beside question 3; the A–D letters are not in the scan.", excerpt: "highway truck. / railway. / water. / ... product of: air,", correction: "Confirm the choice letters against the printed page." },
        { summary: "The key entry for question 4 has no answer line in the scan.", excerpt: "4 4.2.1 RECOGNIZE & ID 9 ... page 99. Table 2.10. / 4.2.1 RECOGNIZE & ID 12 ... nswer: B", correction: "Restore the answer letter from the printed key, page 139." }],
      r: ["4.2.1 (A-8, 12) (B-5), 5.2.1 (A-7).", "page 99. Table 2.10.", "page 29."],
      o: "4..A bill of lading contains valuable information about the origin of the product and is the type of shipping paper used when transporting a product of: air, [column: highway truck. railway. water.]" }),
    rec({ n: 5, key: "5. 4.2.1 RECOGNIZE & ID 12",
      q: "Hazardous occupancies should be identified and evaluated:",
      c: ["enroute to an emergency.", "during preincident planning.", "during training sessions.", "at least once a year."], a: "B",
      notes: ["The key entry number is missing in the scan; the entry (RECOGNIZE & ID 12, Answer B) sits between entries 4 and 6."],
      r: ["4.2.1 (A-1) (B-1).", "page 99.", "page 12."],
      o: "5. Hazardous occupancies should be identified and evaluated: A. enroute to an emergency. B. during preincident planning. C. during training sessions. D. at least once a year." }),
    rec({ n: 6, key: "6. 4.2.1 RECOGNIZE & ID 16",
      q: "The Department of Transportation Placarding System requires a vehicle carrying nonflammable compressed gas to display a placard colored:",
      c: ["red.", "yellow.", "green.", "orange."], a: "C",
      r: ["4.2.1 (A-6, 7, 10) (B-1, 5).", "page 75.", "pages 34-35. Fig. 2-25."],
      o: "6. The Department of Transportation Piacarding System requires a vehicle carrying nonflammable compressed gas to display a placard colored: A. red. B. yellow. C. green. D. orange," }),
    rec({ n: 7, key: "7. 4.2.1 RECOGNIZE & ID 21",
      q: "In the National Fire Protection Association 704 System of Identification, the diamond-shaped placard used for fire hazard is always colored:",
      c: ["blue.", "yellow.", "red.", "white."], a: "C",
      r: ["4.2.1 (A-4) (B-5).", "page 87.", "page 27. Fig. 2-15 [printed \"2.4 5\"]."],
      o: "7. In the National Fire Protection Association 704 System of Identification, the diamond. shaped placard used for fire hazard is always colored: A. blue. B. yellow. C. red. D. white." }),
    rec({ n: 8, key: "8. 4.2.1 RECOGNIZE & ID 23",
      q: "A Hazard Class of 3, within the United Nations (UN) Labeling System indicates a:",
      c: ["flammable gas.", "flammable solid.", "flammable/combustible liquid.", "poisonous liquid."], a: "C",
      r: ["4.2.1 (A-9) (B-5).", "page 76.", "pages 37, 35."],
      o: "8. A Hazard Class of 3, within the United Nations (UN) Labeling System indicates a: A. flammable gas. B. flammable solid. C. flammable/combustible liquid. D. poisonous liquid." }),
    rec({ n: 9, key: "9. 4.2.1 RECOGNIZE & ID 26",
      q: "Using the United Nations/Department of Transportation Labeling System, a flammable liquid would receive a hazard classification of:",
      c: ["1.", "2.", "3.", "4."], a: "C",
      r: ["4.2.1 (A-9) (B-5), 5.2.1 (A-1) (B-5).", "page 83.", "pages 37, 35. Fig. 2-25."],
      o: "9. Using the United Nations/Department of Transportation Labeling System, a flammable liquid would receive a hazard classification of: A. 1. B. 2. Cc. 3. D. 4." }),
    rec({ n: 10, key: "10. 4.2.1 RECOGNIZE & ID 30",
      q: "The background color of a placard that would signify a poisonous substance and that contains skull and crossbones is:",
      c: ["yellow.", "orange.", "red.", "white."], a: "D",
      status: "needs_review",
      issues: [{ summary: "The IFSTA page range is cut off.", excerpt: "5th Edition, pages 76-", correction: "Restore the page range from the key." }],
      r: ["4.2.1 (A-2) (B-1, 7).", { t: "pages 76-[cut off].", x: true }, "page 35. Fig. 2-25."],
      o: "10. The background color of a placard that would signify a poisonous substance and that contains skull and crossbones is: A. yellow. B. orange. C. red. D. white." }),
    rec({ n: 11, key: "11. 4.2.1 RECOGNIZE & ID 31",
      q: "Referring to the United States Military Marking System for Hazardous Materials, an octagon-shaped placard with a #1 on it denotes a:",
      c: ["moderate fire hazard.", "chemical fire hazard.", "mass explosion/detonation.", "mass escape."], a: "C",
      r: ["4.2.1 (A-2, 7) (B-1, 7).", "page 94.", "page 29. Fig. 2-17A."],
      o: "11. Referring to the United States Military Marking System for Hazardous Materials, an octagon-shaped placard with a #1 on it denotes a: A. moderate fire hazard. B. chemical fire hazard. C. mass explosion/detonation. D. mass escape." }),
    rec({ n: 12, key: "12. 4.2.1 RECOGNIZE & ID 32",
      q: "Referring to the United States Military Marking System for Hazardous Materials, the symbol for a mass fire hazard is:",
      c: ["#3 in a triangle.", "#1 in a square.", "#2 in a square.", "#4 in a circle."], a: "A",
      r: ["4.2.1 (A-2, 4, 7) (B-1, 7).", "page 94.", "page 29. Fig. 2-17C."],
      o: "12. Referring to the United States Military Marking System for Hazardous Materials, the symbol for a mass fire hazard is: A. #3 in a triangle. B. #1 in a square. C. #2 in a square. D. #4 ina circle." }),
    rec({ n: 13, key: "13. 4.2.1 RECOGNIZE & ID 33",
      q: "An explosive with a fragment hazard is denoted by the U.S. Military Marking System as a:",
      c: ["#3 in an X.", "#4 in an X.", "#2 in an X.", "#4 in a circle."], a: "C",
      r: ["4.2.1 (A-2, 4, 7) (B-1, 7).", "page 94.", "page 29. Fig. 2-17B."],
      o: "13. An explosive with a fragment hazard is denoted by the U.S. Military Marking System as a: . A. #3 in an X. B. #4 in an X. C. #2 in an X. D. #4 in a circle." }),
    rec({ n: 14, key: "14. 4.2.1 RECOGNIZE & ID 35",
      q: "A tractor-trailer carrying 1001 lbs. of organic peroxides, other than Type B, requires:",
      c: ["a white placard.", "an orange placard.", "a yellow placard.", "no placard."], a: null, hold: true,
      issues: [{ summary: "The key answer for question 14 is unreadable.", excerpt: "44, 4.2.1 RECOGNIZE & ID 35 ... Answer. t", correction: "Restore the answer letter from the printed key, page 141." }],
      notes: ["The key prints this entry's number as \"44\"; it sits between entries 13 and 15."],
      r: ["4.2.1 (A-2, 4, 6) (B-1).", "page 76.", "pages 34, 35. Fig. 2-25."],
      o: "14. A tractor-trailer carrying 1001 Ibs. of organic peroxides, other than Type B, requires: A. a white placard. B. an orange placard. C. a yellow placard. D. no placard." }),
    rec({ n: 15, key: "15. 4.2.1 RECOGNIZE & ID 36",
      q: "The National Fire Protection Association (NFPA) 704 System provides the:",
      c: ["general hazard identification.", "product's chemical name.", "four-digit UN number.", "number used to look up the product's name."], a: "A",
      notes: ["The key prints this entry's number as \"45\"; it sits between entries 14 and 16."],
      r: ["4.2.1 (A-2, 4) (B-7).", "page 86.", "page 26."],
      o: "15. The National Fire Protection Association (NFPA) 704 System provides the: A. general hazard identification. B. product's chemical name. C. four-digit UN number. D. number used to look up the product's name." }),
    rec({ n: 16, key: "16. 4.2.1 RECOGNIZE & ID 38",
      q: "The primary consideration in determining whether a facility is required to have Safety Data Sheet information is whether the facility:",
      c: ["is located within 1000 feet of residential neighborhoods.", "has chemicals that are used in the workplace.", "has 24-hour security.", "has an area under one roof that is greater than 250,000 square feet."], a: "B",
      r: ["4.2.1 (A-11) (B-1).", "page 98.", "page 25."],
      o: "16. The primary consideration in determining whether a facility is required to have Safety Data Sheet information is whether the facility: A. is located within 1000 feet of residential neighborhoods. B. has chemicals that are used in the workplace. C. has 24-hour security. D. has an area under one roof that is greater than 250,000 square feet." }),
    rec({ n: 17, key: "17. 4.2.1 RECOGNIZE & ID 41",
      q: "A Dangerous Cargo Manifest may be in the:",
      c: ["cab of the vehicle.", "cargo hold.", "cockpit.", "wheelhouse or bridge."], a: "D",
      notes: ["The key prints this entry's number as \"47\"; it sits between entries 16 and 18."],
      r: ["4.2.1 (A-1, 2) (B-1, 5), 4.3.1 (A-1).", "page 99.", "page 30."],
      o: "17. A Dangerous Cargo Manifest may be in the: A. cab of the vehicle. B. cargo hold. C. cockpit. D. wheelhouse or bridge" }),
    rec({ n: 18, key: "18. 4.2.1 RECOGNIZE & ID 43",
      q: "Who is responsible for care and control of a Dangerous Cargo Manifest?",
      c: ["Captain or master", "Conductor/crew", "Driver", "Pilot"], a: "A",
      notes: ["The key prints this entry's number as \"48\"; it sits between entries 17 and 19."],
      r: ["4.2.1 (A-1, 2) (B-1, 5), 4.3.1 (A-1).", "page 99.", "page 30."],
      o: "18. Who is responsible for care and control of a Dangerous Cargo Manifest? A. Captain or master B. Conductor/crew C. Driver D. Pilot" }),
    rec({ n: 19, key: "19. 4.2.1 RECOGNIZE & ID 46",
      q: "The Environmental Protection Agency signal word - Warning - indicates:",
      c: ["high level of toxicity.", "moderate level of toxicity.", "low level of toxicity.", "intermediate level of toxicity."], a: "B",
      status: "needs_review",
      issues: [{ summary: "Choices A and B are scrambled across two lines in the scan; the printed letters were used.", excerpt: "indicates: Po B. moderate level of toxicit / A. high level of toxicit : , y.", correction: "Confirm choices A and B against the printed page." }],
      r: ["4.2.1 (A-2) (B-1).", "page 96.", "page 49."],
      o: "19. The Environmental Protection Agency signal word - Warning - indicates: Po B. moderate level of toxicit A. high level of toxicit : , y. C. low level of toxicity. D. intermediate level of toxicity." }),
    rec({ n: 20, key: "20. 4.2.1 RECOGNIZE & ID 49",
      q: "What would be used to determine the name of a hazardous material located in a facility?",
      c: ["National Fire Protection Association 704 diamond", "Emergency Response Guidebook", "Shipping papers", "Safety Data Sheets"], a: "D",
      r: ["4.2.1 (A-11) (B-7).", "page 25.", "page 25."],
      o: "20. What would be used to determine the name of a hazardous material located in a facility? A. National Fire Protection Association 704 diamond B. Emergency Response Guidebook C. Shipping papers D. Safety Data Sheets" }),
    rec({ n: 21, key: "21. 4.2.1 RECOGNIZE & ID 52",
      q: "Which Federal agency is involved in the regulation of hazardous materials and/or wastes?",
      c: ["Department of Transportation", "Local Emergency Planning Commission", "Department of the Interior", "Chemical Transportation Emergency Center"], a: "A",
      r: ["4.2.1 (A-9) (B-7).", "page 74.", "page 27."],
      o: "21. Which Federal agency is involved in the regulation of hazardous materials and/or wastes? A. Department of Transportation B. Locai Emergency Planning Commission C. Department of the Interior D. Chemical Transportation Emergency Center" }),
    rec({ n: 22, key: "22. 4.2.1 RECOGNIZE & ID 56",
      q: "The primary hazard of a Department of Transportation Hazard Class 5 material is:",
      c: ["radiation.", "oxidation.", "spontaneously combustible.", "poison."], a: "B",
      status: "needs_review",
      issues: [{ summary: "Both textbook citations are garbled.", excerpt: "5th Edition, pages at ie rig. 23 / 1 Pages 37, 35, Fig, 29", correction: "Restore the IFSTA pages and figure and the Jones and Bartlett figure from the key." }],
      r: ["4.2.1 (A-2) (B-7).", { t: "pages unreadable. Fig. 2.3[?].", x: true }, { t: "pages 37, 35. Fig. 2-[unreadable].", x: true }],
      o: "22. The primary hazard of a Department of Transportation Hazard Class 5 materil is: A. radiation. B. oxidation. C. spontaneously combustible. D. poison." }),
    rec({ n: 23, key: "23. 4.2.1 RECOGNIZE & ID 58",
      q: "Which section of the Emergency Response Guidebook provides the fire, explosion, and health hazard information for the material identified by the first responder?",
      c: ["Green", "Yellow", "Orange", "Blue"], a: "C",
      r: ["4.2.1 (A-9) (B-7).", "pages 75-76. Fig. 2.3.", "pages 35-36."],
      o: "23. Which section of the Emergency Response Guidebook provides the fire, explosion, and health hazard information for the material identified by the first responder? A. Green B. Yellow C. Orange D. Blue" }),
    rec({ n: 24, key: "24. 4.2.1 RECOGNIZE & ID 62",
      q: "The chemicals listed in highlighted type in the Emergency Response Guidebook were selected because:",
      c: ["they present a toxic inhalation hazard.", "their vapors are explosive.", "they create corrosive vapors.", "the actions listed in the orange section will not be effective for these chemical."], a: "A",
      r: ["4.2.1 (A-9) (B-7).", "page 118.", "page 36."],
      o: "24. The chemicais listed in highlighted type in the Emergency Response Guidebook were selected because: A. they present a toxic inhalation hazard. B. their vapors are explosive. C. they create corrosive vapors. . D. the actions listed in the orange section will not be effective for these chemical." }),
    rec({ n: 25, key: "25. 4.2.1 RECOGNIZE & ID 64",
      q: "The DOT Hazard Class 1 consists of:",
      c: ["explosives.", "flammable liquids.", "poisons.", "corrosives."], a: "A",
      r: ["4.2.1 (A-9) (B-7).", "pages 72, 76, 78. Fig. 2.37, Fig. 2.40, Table 2.5.", "pages 37, 35. Fig. 2-25."],
      o: "25. The DOT Hazard Class 1 consists of: A. explosives. B. flammable liquids. C. poisons. D. corrosives." }),
    rec({ n: 26, key: "26. 4.2.1 RECOGNIZE & ID 68",
      q: "The Department of Transportation Hazard Class 5 consists of:",
      c: ["oxidizers.", "poisons.", "flammable liquids.", "flammable solids."], a: "A",
      r: ["4.2.1 (A-2, 6) (B-1).", "pages 72, 76, 78, 83, 84. Fig. 2.37, Fig. 2.40, Table 2.5.", "pages 37, 35. Fig. 2-25."],
      o: "26. The Department of Transportation Hazard Class 5 consists of: A. oxidizers. B. poisons. C. flammable liquids. D. flammable solids." }),
    rec({ n: 27, key: "27. 4.2.1 RECOGNIZE & ID 69",
      q: "The Department of Transportation Hazard Class 6 consists of:",
      c: ["oxidizers.", "poisons.", "radioactive substances.", "flammable liquids."], a: "B",
      r: ["4.2.1 (A-2, 6) (B-1).", "pages 73, 76, 78, 84. Fig. 2.37, Fig. 2.40, Table 2.5.", "pages 37, 35. Fig. 2-25."],
      o: "27. The Department of Transportation Hazard Class 6 consists of: A. oxidizers. B. poisons. C. radioactive substances. D. flammable liquids." }),
    rec({ n: 28, key: "28. 4.2.1 RECOGNIZE & ID 79",
      q: "The active ingredients on a pesticide label will be:",
      c: ["listed by name.", "listed but not specifically named.", "listed only by chemical compound.", "listed only as a percentage."], a: "A",
      r: ["4.2.1 (A-1) (B-3).", "page 96.", "page 48. Fig. 3-1."],
      o: "28. The active ingredients on a pesticide label will be: A. listed by name. B. listed but not specifically named. C. listed only by chemical compound. D. listed only as a percentage." }),
    rec({ n: 29, key: "29. 4.2.1 RECOGNIZE & ID 81",
      q: "The statement, \"Keep Away From Children,\" found on a pesticide label is an example of:",
      c: ["a precautionary statement.", "an incompatibility statement.", "a pest control warning statement.", "a signal word statement."], a: "A",
      r: ["4.2.1 (A-2, 3, 6) (B-1, 5, 6), 5.2.1 (A-7).", "page 96. Fig. 2.52.", "page 49."],
      o: "29. The statement, \"Keep Away From Children,\" found on a pesticide label is an example of: A. a precautionary statement. B. an incompatibility statement. C. a pest control warning statement. D. a signal word statement." }),
    rec({ n: 30, key: "30. 4.2.1 RECOGNIZE & ID 84",
      q: "A common design feature of cylinders is a:",
      c: ["pressure relief device.", "fill cap.", "manual-control vent.", "air monitoring alarm."], a: "A",
      r: ["4.2.1 (A-2, 3, 8(m)) (B-1).", "page 281.", "page 23."],
      o: "30. A common design feature of cylinders is a: A. pressure relief device. B. fill cap. C. manual-control vent. D. air monitoring alarm." }),
    rec({ n: 31, key: "31. 4.2.1 RECOGNIZE & ID 85",
      q: "Hazard Class 3 includes:",
      c: ["black powder.", "gasoline.", "ammonium nitrate.", "magnesium."], a: "B",
      r: ["4.2.1 (A-1).", FIG237, "page 37."],
      o: "31. Hazard Class 3 includes: A. black powder. B. gasoline. C. ammonium nitrate. D. magnesium." }),
    rec({ n: 32, key: "32. 4.2.1 RECOGNIZE & ID 88",
      q: "Which hazard class is represented by the placard drawing below?",
      c: ["Explosives", "Nonflammable gases", "Flammable solids", "Oxidizers"], a: "C", hold: true,
      image: "Placard drawing referenced by the stem (\"the placard drawing below\"); the OCR shows only \"4 N\" where the drawing sits. The scan does not include the drawing.",
      issues: [{ summary: "The question depends on a placard drawing that is not in the scan.", excerpt: "32. Which hazard class is represented by the placard drawing below? 4 N", correction: "Add the placard drawing before scoring." },
        { summary: "The IFSTA page citation is cut off.", excerpt: "5th Edition, pages 76,", correction: "Restore the page range from the key." }],
      r: ["4.2.1 (A-10) (B-5), 5.2.1 (A-3) (B-5).", { t: "pages 76, [cut off].", x: true }, "page 35. Fig. 2-25."],
      o: "32. Which hazard class is represented by the placard drawing below? 4 N A. Explosives B. Nonflammable gases C. Flammable solids D. Oxidizers" }),
    rec({ n: 33, key: "33. 4.2.1 RECOGNIZE & ID 91",
      q: "The hazard class represented by the placard illustration below is:",
      c: ["dangerous when wet.", "combustibles.", "health hazard.", "oxidizers."], a: "A", hold: true,
      image: "Placard illustration referenced by the stem (\"the placard illustration below\"). The scan does not include the illustration.",
      issues: [{ summary: "The question depends on a placard illustration that is not in the scan.", excerpt: "33. The hazard class represented by the placard illustration below is:", correction: "Add the placard illustration before scoring." }],
      r: ["4.2.1 (A-10) (B-5), 5.2.1 (A-3).", "pages 75, 186-188. Fig. 4.68, Table 4.8.", "page 35. Fig. 2-25."],
      o: "33. The hazard class represented by the placard illustration below is: A. dangerous when wet. B. combustibles. C. health hazard. ~ _- D. oxidizers." }),
    rec({ n: 34, key: "34. 4.3.1 INIT PROT ACT 2",
      q: "People remaining inside until the danger passes is:",
      c: ["protective actions.", "isolation areas.", "restricted access.", "sheltering in place."], a: "D",
      r: ["4.3.1 (A-2) (B-3), 5.2.1 (A-12) (B-8).", "page 128.", "page 110."],
      o: "34. People remaining inside until the danger passes is: A. protective actions. B. isolation areas. C. restricted access. D. sheltering in place." }),
    rec({ n: 35, key: "35. 4.3.1 INIT PROT ACT 4",
      q: "One of the roles of the first responder at the awareness level during a Hazmat incident is to:",
      c: ["plug the leak.", "operate a remote shut off.", "isolate the area.", "dike around a spill."], a: "C",
      status: "needs_review",
      issues: [{ summary: "The IFSTA page is missing from the citation.", excerpt: "(B- 3)IFSTA, Hazardous Materials for First Responders, Sth Edition, / Jones and Bartlett ... page 19.", correction: "Restore the IFSTA page from the key." }],
      r: ["4.3.1 (A-2) (B-3).", { t: "page missing.", x: true }, "page 19."],
      o: "35. One of the roles of the first responder at the awareness level during a Hazmat incident is to: A. plug the leak. B. operate a remote shut off. C. isolate the area. D. dike around a spill." }),
    rec({ n: 36, key: "36. 4.3.1 INIT PROT ACT 10",
      q: "To minimize exposure to hazards, the evacuation efforts should:",
      c: ["be led by the senior law enforcement officer.", "start with those in the most danger.", "be performed by trained hazardous materials technicians.", "establish a safe area downwind of the incident."], a: "B",
      r: ["4.3.1 (A-2, 3) (B-2, 6).", "page 344.", "page 110."],
      o: "36. To minimize exposure to hazards, the evacuation efforts should: A. be led by the senior law enforcement officer. B. start with those in the most danger. C. be performed by trained hazardous materials technicians. D. establish a safe area downwind of the incident." }),
    rec({ n: 37, key: "37. 4.4.1 NOTIFICATIONS 2",
      q: "First responders trained to the Awareness Level can:",
      c: ["select and use proper personal protective equipment.", "implement basic decontamination measures.", "realize the need for additional resources and make the appropriate notifications.", "apply basic hazard and risk assessment techniques."], a: "C",
      r: ["4.4.1 (A-1) (B-2).", "page 18.", "page 7."],
      o: "37. First responders trained to the Awareness Level can: A. select and use proper personal protective equipment. B. implement basic decontamination measures. C. realize the need for additional resources and make the appropriate NOtifications D. apply basic hazard and risk assessment techniques." }),
    rec({ n: 38, key: "38. 4.4.1 NOTIFICATIONS 3",
      q: "The lead investigating agency during a terrorist attack is the:",
      c: ["Bureau of Alcohol Tobacco and Firearms.", "Federal Emergency Management Association.", "U.S. Fire Administration.", "Federal Bureau of Investigation."], a: "D",
      status: "needs_review",
      issues: [{ summary: "The NFPA and IFSTA citations are garbled.", excerpt: "NFPA 1072, 4.4. 4). dition, page 361. vardous Materials for First Responders, th Edition, ps", correction: "Restore the NFPA subsection and confirm the IFSTA page (read as 361) from the key." }],
      r: [{ t: "4.4.[unreadable].", x: true }, { t: "page 361 (partly unreadable).", x: true }, "pages 246, 263."],
      origCite: "Reference: NFPA 1072, 4.4. 4). dition, page 361. vardous Materials for First Responders, th Edition, ps Jonna end bartall, Hazardous Materials Awareness and Operations, 3rd Ed, page 246,263,",
      o: "38. The lead investigating agency during a terrorist attack is the: A. Bureau of Alcohol Tobacco and Firearms. B. Federal Emergency Management Association. C. U.S. Fire Administration. D. Federal Bureau of Investigation." }),
    rec({ n: 39, key: "39. 4.4.1 NOTIFICATIONS 5",
      q: "During the notification process, tactical channels may be assigned to:",
      c: ["increase the span of control.", "the media to increase site safety awareness.", "ensure dedicated radio channels are available.", "expedite the notification process to CHEMTREC."], a: "C",
      r: ["4.4.1 (A-1-3) (B-1-2).", "page 463.", "page 141."],
      o: "39. During the notification process, tactical channels may be assigned to: A. increase the span of control. B. the media to increase site safety awareness. C. ensure dedicated radio channels are available. D. expedite the notification process to CHEMTREC." }),
    rec({ n: 40, key: "40. 5.2.1 ID POT HAZARD 1",
      q: "When dealing with a radiological incident involving a leak or spill, what exposure guidelines should the hazmat first responder use to minimize radioactive contamination?",
      c: ["Time, distance, half-life", "Ionizing radiation, non-ionizing radiation, half-life", "Time, distance, shielding", "Alpha particles, beta particles, gamma rays"], a: "C",
      notes: ["Choice B is printed \"lonizing radiation, non-iodizing radiation\" in the scan; the obvious spelling was cleaned."],
      r: ["5.2.1 (A-4, 8([unreadable], g), 10(c)) (B-2, 4, 8), 6.6.1 (A-4, 5, 6) (B-1, 2, 5).", "page 168.", "pages 62, 108."],
      o: "40. When dealing with a radiological incident involving a leak or spill, what exposure guidelines shouid the hazmat first responder use to minimize radioactive contamination? A. Time, distance, half-life B. lonizing radiation, non-iodizing radiation, half-life C. Time, distance, shielding D. Alpha particles, beta particles, gamma rays" }),
    rec({ n: 41, key: "41. 5.2.1 ID POT HAZARD 3",
      q: "The initial part of assessment is:",
      c: ["calling for the appropriate help to mitigate the incident.", "recognizing the presence of hazardous materials.", "determining the appropriate actions to be taken recommended by the Emergency Response Guidebook.", "securing the area of the emergency."], a: "B",
      r: ["5.2.1 (A-1-3) (B-1-5).", "pages 293, 114.", "page 18."],
      o: "41. The initial part of assessment is: . A. calling for the appropriate help to mitigate the incident. B. recognizing the presence of hazardous materials. C. determining the appropriate actions to be taken recommended by the Emergency Response Guidebook. D. securing the area of the emergency." }),
    rec({ n: 42, key: "42. 5.2.1 ID POT HAZARD 12",
      q: "During a suspected terrorist event, warning indicators that responders should be alert are:",
      c: ["several people with minor injuries.", "placard containers.", "public gathering.", "secondary devices."], a: "D",
      r: ["5.2.1 (A-10(d), 11, 12) (B-3, 4, 7, 8).", "page 368.", "page 100."],
      o: "42. During a suspected terrorist event, warning indicators that responders should be alert are: A. several people with minor injuries. B. placard containers. C. public gathering. D. secondary devices." }),
    rec({ n: 43, key: "43. 5.2.1 ID POT HAZARD 15",
      q: "If a hazardous material incident involves a leaking flammable substance, the first responders should immediately remove all:",
      c: ["ignition sources.", "upwind ignition sources.", "large combustible tanks.", "fire equipment and personnel."], a: "A",
      r: ["5.2.1 (A-1, 8(a, d, e, f)) (B-2, 5, 8).", "page 123.", "page 135."],
      o: "43. If a hazardous material incident involves a leaking flammable substance, the first responders should immediately remove all: A. ignition sources. B. upwind ignition sources. C. large combustible tanks. D. fire equipment and personnel." }),
    rec({ n: 44, key: "44. 5.2.1 ID POT HAZARD 18",
      q: "Which is required on a pipeline marker?",
      c: ["Pipeline owner's phone number", "Size of pipeline", "Pipeline depth underground", "Name of emergency responder agency"], a: "A",
      r: ["5.2.1 (A-1, 3, 4, 7) (B-2-6).", "page 276.", "pages 32, 34. Fig. 2-22."],
      o: "44. Which is required on a pipeline marker? A. Pipeline owner's phone number B. Size of pipeline C. Pipeline depth underground D. Name of emergency responder agency" }),
    rec({ n: 45, key: "45. 5.2.1 ID POT HAZARD 23",
      q: "The manufacturing and labeling of pesticides is regulated by the:",
      c: ["Occupational Safety and Health Administration.", "Environmental Protection Agency.", "Comprehensive Environmental Response, Compensation and Liability Act.", "Federal Emergency Management Association."], a: "B",
      r: ["5.2.1 (A-1, 2, 3, 8(b, c, d, e, f, i, l, m, n), 9, 10(a), 11, 12) (B-1-3, 8).", "page 141.", "pages 48-49."],
      o: "45. The manufacturing and labeling of pesticides is regulated by the: A. Occupational Safety and Health Administration. B. Environmental Protection Agency. C. Comprehensive Environmental Response, Compensation and Liability Act. D. Federal Emergency Management Association." }),
    rec({ n: 46, key: "46. 5.2.1 ID POT HAZARD 25",
      q: "What organization provides an emergency call center for first responders at a hazmat emergency?",
      c: ["The manufacturer", "The Local Emergency Planning Committee", "CHEMTREC®", "Occupational Safety and Health Administration"], a: "C",
      status: "needs_review",
      notes: ["Question 47's choices are printed in a second column beside this question's choices in the scan; this question's lettered choices are legible."],
      issues: [{ summary: "Both textbook page citations are garbled.", excerpt: "Jones and barvietl, Hazardous Materials Awareness and O i jFSTA, Hazardous Materials for First Responders, 5th Edition page ‘S08 *a, page 82.", correction: "Restore the IFSTA and Jones and Bartlett pages from the key, page 145." }],
      r: ["5.2.1 (A-1, 3, 4, 6).", U, { t: "page 82 (attribution unclear).", x: true }],
      o: "46. What organization provides an emergency call center for first responders at a hazmat emergency? A. The manufacturer Nerve agents B. The Local Emergency Planning Committee Vesicants C. CHEMTREC® oo : Nuclear agents D. Occupational Safety and Health Administration" }),
    rec({ n: 47, key: "47. 5.2.1 ID POT HAZARD 30",
      q: "The acronym SLUDGEM is used to describe the signs and symptoms of exposure to which of the categories of warfare agents?",
      c: ["Nerve agents", "Vesicants", "Nuclear agents", "Biological agents"], a: "A", hold: true,
      issues: [{ summary: "The choices are printed as an unlabeled column beside question 46; the A–D letters are not in the scan.", excerpt: "Nerve agents / Vesicants / Nuclear agents / ... warfare agents? Biological agents", correction: "Confirm the choice letters against the printed page before scoring with the key answer A." }],
      r: ["5.2.1 (A-10(a, b)) (B-4).", "page 392.", "pages 91-92. Table 4-3."],
      o: "47:. The acronym SLUDGEM is used to describe the signs and symptoms of exposure to which of the categories of warfare agents? [column: Nerve agents Vesicants Nuclear agents Biological agents]" }),
    rec({ n: 48, key: "48. 5.2.1 ID POT HAZARD 96",
      q: "Large tanks with hemispherical heads on both ends are:",
      c: ["cryogenic liquid.", "corrosive liquid.", "dry bulk.", "high pressure."], a: "D",
      r: ["5.2.1 (A-2) (B-1).", "page 243.", "page 79. Fig. 4-17."],
      o: "48. Large tanks with hemispherical heads on both ends are: A. cryogenic liquid. B. corrosive liquid. C. dry bulk. ; D. high pressure." }),
    rec({ n: 49, key: "49. 5.2.1 ID POT HAZARD 112",
      q: "Containers labeled with a Hazard Classification of 4 contain:",
      c: ["explosives.", "flammable gases.", "flammable solids.", "flammable liquids."], a: "C",
      r: ["5.2.1 (A-1).", FIG237, "page 37."],
      o: "49. Containers labeled with a Hazard Classification of 4 contain: A. explosives. B. flammable gases. C. flammable solids. D. flammable liquids." }),
    rec({ n: 50, key: "50. 5.2.1 ID POT HAZARD 113",
      q: "Alpha particles are:",
      c: ["gas particles.", "ionizing radiation like x-rays.", "particles with weight and mass.", "deadly radiation."], a: "C",
      status: "needs_review",
      issues: [{ summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A-.80).", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, "page 163.", "page 61."],
      o: "50. Alpha particles are: A. gas particles. B. ionizing radiation like x-rays. C. particles with weight and mass. D. deadly radiation." }),
    rec({ n: 51, key: "51. 5.2.1 ID POT HAZARD 114",
      q: "Which statement is true regarding neutron radiation?",
      c: ["They are highly penetrating.", "It is commonly used in commercial and industrial operations.", "They are easy to measure in the field.", "They are usually found in common pharmacies."], a: "A",
      status: "needs_review",
      issues: [{ summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A- 8())).", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, "page 165.", "page 62."],
      o: "51. Which statement is true regarding neutron radiation? A. They are highly penetrating. B. It is commonly used in commercial and industrial operations. C. They are easy to measure in the field. D. They are usually found in common pharmacies." }),
    rec({ n: 52, key: "52. 5.2.1 ID POT HAZARD 126",
      q: "A chemical with a vapor density of greater than one will tend to:",
      c: ["dissipate immediately when exposed to air.", "collect in low areas and below-grade places.", "lift into the air.", "spontaneously combust when exposed to air."], a: "B",
      notes: ["The question number is printed \"2.\" in the scan; it sits between questions 51 and 53 and matches key entry 52."],
      r: ["5.2.1 (A-8(m)).", "page 148.", "page 57."],
      o: "2. A chemical with a vapor density of greater than one will tend to: A. dissipate immediately when exposed to air. B. collect in low areas and below-grade places. C. lift into the air. D. spontaneously combust when exposed to air." }),
    rec({ n: 53, key: "53. 5.2.1 ID POT HAZARD 127",
      q: "Chemicals with specific gravities greater than one tend to:",
      c: ["float on water.", "sink.", "vaporize into the air.", "mix."], a: "B",
      r: ["5.2.1 (A-8(k)).", "page 151.", "page 57."],
      o: "53. Chemicals with specific gravities greater than one tend to: A. float on water. B. sink. C. vaporize into the air. D. mix." }),
    rec({ n: 54, key: "54. 5.2.1 ID POT HAZARD 128",
      q: "A liquid's ability to mix with water is:",
      c: ["solubility.", "surface tension.", "water reactivity.", "instability."], a: "A",
      r: ["5.2.1 (A-8(m)).", "page 190.", "page 58."],
      o: "54. A liquid's ability to mix with water is: A. solubility. B. surface tension. C. water reactivity. D. instability." }),
    rec({ n: 55, key: "55. 5.2.1 ID POT HAZARD 129",
      q: "A reaction that is associated with over-pressurization of closed containers and occurs at a rate of one second or less is a:",
      c: ["rapid relief.", "boiling liquid expanding vapor explosion.", "crack.", "low pressure release."], a: "B",
      r: ["5.2.1 (A-8(d), 12).", "page 147.", "page 51."],
      o: "55. A reaction that is associated with over-pressurization of closed containers and occurs at a rate of one second or less is a: A. rapid relief. B. boiling liquid expanding vapor explosion. C. crack. D. low pressure release." }),
    rec({ n: 56, key: "56. 5.2.1 ID POT HAZARD 141",
      q: "_____ is the ratio of the weight of a volume of liquid to the weight of an equal volume of water.",
      c: ["Flammable/explosive range", "Flash point", "Specific gravity", "Vapor density"], a: "C",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("56. is the ratio of the weight of a volume of liquid to the weight of an equal volume of water.")],
      r: ["5.2.1 (A-8(k)).", "page 151.", "page 57."],
      o: "56. is the ratio of the weight of a volume of liquid to the weight of an equal volume of water. A. Fiammable/explosive range B. Flash point C. Specific gravity D. Vapor density" }),
    rec({ n: 57, key: "57. 5.2.1 ID POT HAZARD 145",
      q: "Determining whether a vapor will rise, or fall is:",
      c: ["vapor dispersion.", "vapor density.", "vaporization.", "specific gravity."], a: "B",
      r: ["5.2.1 (A-8(m)).", "pages 148-149.", "page 56."],
      o: "57. Determining whether a vapor will rise, or fall is: A. vapordispersion.: _-. B. vapor density. C. vaporization. D. specific gravity." }),
    rec({ n: 58, key: "58. 5.2.1 ID POT HAZARD 156",
      q: "Water solubility is the:",
      c: ["degree to which a substance will mix with water.", "percentage of an acid or base dissolved in water.", "measure of a substance's tendency to deteriorate another substance.", "ratio of the weight of a volume of liquid or solid to the weight of an equal volume of water."], a: "A",
      r: ["5.2.1 (A-8(m)).", "page 149.", "page 58."],
      o: "58. Water solubility is the: A. degree to which a substance will mix with water. B. percentage of an acid or base dissolved in water. C. measure of a substance's tendency to deteriorate another substance.. D. ratio of the weight of a volume of liquid or solid to the weight of an equal volume of water." }),
    rec({ n: 59, key: "59. 5.3.1 ID ACTION OPT 5",
      q: "A person who is repeatedly exposed to a chemical over a long period of time may develop:",
      c: ["etiological changes.", "acute health hazard.", "chronic health hazard.", "chemical asphyxia."], a: "C",
      r: ["5.3.1 (A-15).", "page 21.", "pages 63, 68."],
      o: "59. A person who is repeatedly exposed to a chemical over a long period of time may develop: A. etiological changes. B. acute health hazard. C. chronic health hazard. D. chemical asphyxia." }),
    rec({ n: 60, key: "60. 5.3.1 ID ACTION OPT 14",
      q: "To contact the shipper for hazard and response information, a firefighter can obtain information number from:",
      c: ["Computer-Aided Management of Emergency Operations.", "the Chemical Abstracts Service registry number.", "the Emergency Response Guide.", "the shipping papers."], a: "D",
      notes: ["The key prints the reference number as \"714\"; it was read as 14, matching the II-1 and II-3 keys for the same item."],
      r: ["5.3.1 (A-8), 4.4.1 (A-1).", "page 99.", "page 29."],
      o: "60. To contact the shipper for hazard and response information, a firefighter can obtain information number from: A. Computer-Aided Management of Emergency Operations. B. the Chemical Abstracts Service registry number. C. the Emergency Response Guide. D. the shipping papers." }),
    rec({ n: 61, key: "61. 5.3.1 ID ACTION OPT 16",
      q: "The firefighter may obtain appropriate Safety Data Sheet information from:",
      c: ["Computer-Aided Management of Emergency Operations.", "the National Response Center.", "Occupational Safety and Health Administration.", "the employer of the facility."], a: "D",
      r: ["5.3.1 (A-7).", "pages 88, 199.", "page 25."],
      o: "61. The firefighter may obtain appropriate Safety Data Sheet information from: A. Computer-Aided Management of Emergency Operations. B. the National Response Center. C. Occupational Safety and Health Administration. D. the employer of the facility." }),
    rec({ n: 62, key: "62. 5.3.1 ID ACTION OPT 28",
      q: "The steps that are taken to preserve the health and safety of emergency responders and the public during an incident involving releases of hazardous materials are:",
      c: ["protective actions.", "isolating the hazard area and denying entry.", "evacuation procedures.", "protect in place procedures."], a: "A",
      status: "needs_review",
      issues: [{ summary: "The IFSTA page is garbled.", excerpt: "oh Ecition page 4 27.", correction: "Confirm the IFSTA page (read as 127, matching the II-1 key) against the printed key." }],
      r: ["5.3.1 (A-1-5, 12-13) (B-1-2), 5.4.1 (A-1-6) (B-1-2).", { t: "page 127 (garbled in the scan).", x: true }, "page 137."],
      o: "62. The steps that are taken to preserve the health and safety of emergency responders and the public during an incident involving releases of hazardous materials are: A. protective actions. . B. isolating the hazard area and denying entry. C. evacuation procedures. . D. protect in place procedures." }),
    rec({ n: 63, key: "63. 5.3.1 ID ACTION OPT 29",
      q: "With respect to exposure, long term is:",
      c: ["minutes and hours.", "days, weeks, and years.", "a century or more.", "years and generations."], a: "D",
      notes: ["The key lists no Jones and Bartlett reference for this entry."],
      r: ["5.3.1 (A-13, 17).", "page 225.", null],
      o: "63. With respect to exposure, long term is: A. minutes and hours. B. days, weeks, and years. C. a century or more. D. years and generations." }),
    rec({ n: 64, key: "64. 5.4.1 ACT PLAN IMPLE 3",
      q: "At a terrorism incident, responders must be aware that:",
      c: ["the incident may have taken place in a high crime area, so they should wait for the police before taking any action.", "the terrorist may be on the scene waiting for responders to arrive before striking again.", "the terrorist will not intentionally target responders, so they should consider the scene safe except for any hazardous materials present.", "scene control at criminal incidents is solely the responsibility of law enforcement, so they should focus on other activities."], a: "B",
      notes: ["The question number is printed \"4.\" in the scan; it sits between questions 63 and 65 and matches key entry 64."],
      r: ["5.4.1 (A-1) (B-1, 2), 5.2.1 (A-12, 11) (B-8).", "page 129.", "page 100."],
      o: "4. At a terrorism incident, responders must be aware that: A. the incident may have taken place in a high crime area, so they shouid wait for the police before taking any action. B. the terrorist may be on the scene waiting for responders to arrive before striking again. C. the terrorist will not intentionally target responders, so they should consider the scene safe except for any hazardous materials present. D. scene control at criminal incidents is solely the responsibility of Iaw enforcement, so they should focus on other activities." }),
    rec({ n: 65, key: "65. 5.4.1 ACT PLAN IMPLE 5",
      q: "The collection of evidence at a terrorist event is primarily the responsibility of:",
      c: ["the hazmat teams.", "the fire department.", "law enforcement.", "the arson investigator."], a: "C",
      notes: ["The question number is missing in the scan; the item sits between questions 64 and 66 and matches key entry 65."],
      r: ["5.4.1 (A-5) (B-3).", "page 654.", "page 246."],
      o: "The collection of evidence at a terrorist event is primarily the responsibility of: A. the hazmat teams. B. the fire department. C. law enforcement. D. the arson investigator." }),
    rec({ n: 66, key: "66. 5.4.1 ACT PLAN IMPLE 8",
      q: "The immediate concern with combustible liquid spills is to:",
      c: ["apply aqueous film forming foam to the combustible liquid.", "prevent ignition.", "dike storm drains along collection route.", "ignite fuel to allow the combustible materials to burn off."], a: "B",
      r: ["5.4.1 (A-1, 9) (B-1, 2).", "pages 123, 616.", "page 135."],
      o: "66. The immediate concern with combustible liquid spills is to: A. apply aqueous film forming foam to the combustible liquid. B. prevent ignition. C. dike storm drains along collection route. D. ignite fuel to allow the combustible materials to burn off." }),
    rec({ n: 67, key: "67. 5.4.1 ACT PLAN IMPLE 10",
      q: "Directions: Read the following statements regarding vapor dispersion and select the correct answer from choices A through D.",
      statements: [
        "Statement 1: Vapor dispersion involves using water spray or fans to intentionally move vapors away from certain areas.",
        "Statement 2: Vapor dispersion is always a good idea when flammable substances are the problem.",
        "Statement 3: Vapor dispersion is only effective with materials that are water soluble."
      ],
      c: ["Statement 1 is false; statements 2 and 3 are true.", "Statement 1 is true; statements 2 and 3 are false.", "Statements 1 and 2 are true; statement 3 is false.", "All three statements are true."], a: "B",
      r: ["5.4.1 (A-1) (B-1, 2), 5.3.1 (A-3).", "pages 152, 312, 616. Table 6.1.", "page 277."],
      o: "67. Directions: Read the following statements regarding vapor dispersion and select the correct answer from choices A through D. Statement 1: Vapor dispersion involves using water spray or fans to intentionally move vapors away from certain areas. Statement 2: Vapor dispersion is always a good idea when flammable substances are the problem. Statement 3: Vapor dispersion is only effective with materials that are water soluble. A. Statement 1 is false; statements 2 and 3 are true. B. Statement 1 is true; statements 2 and 3 are false. C. Statements 1 and 2 are true; statement 3 is false. D. All three statements are true." }),
    rec({ n: 68, key: "68. 5.4.1 ACT PLAN IMPLE 15",
      q: "The area that exists just outside the hot/exclusion zone is the:",
      c: ["warm zone.", "command zone.", "support zone.", "staging area."], a: "A",
      r: ["5.4.1 (A-1) (B-1, 2).", "page 335. Fig. 7.13.", "pages 137, 136, 153. Fig. 6-5."],
      o: "68. The area that exists just outside the hot/exclusion zone is the: A. warm zone. B. command zone. C. support zone. D. staging area." }),
    rec({ n: 69, key: "69. 5.4.1 ACT PLAN IMPLE 18",
      q: "Which protective action must be taken during shelter in-place protection?",
      c: ["Close all windows.", "Establish a water curtain.", "Use positive pressure to protect the structure.", "Ensure heating, ventilation, air conditioning system remains operating."], a: "A",
      r: ["5.4.1 (A-3), 4.3.1 (A-1-3) (B-1, 2, 3, 5).", "page 346.", "page 139."],
      o: "69. Which protective action must be taken during shelter in-place protection? A. Close all windows. B. Establish a water curtain. C. Use positive pressure to protect the structure. D. Ensure heating, ventilation, air conditioning system remains operating." }),
    rec({ n: 70, key: "70. 5.4.1 ACT PLAN IMPLE 19",
      q: "When sheltering people in place, the citizens should be directed to:",
      c: ["close all heating, ventilation, and air-conditioning systems.", "open windows for air exchange.", "keep all heating, ventilation, and air-conditioning systems running.", "periodically open the doors to relieve the pressure."], a: "A",
      status: "needs_review",
      issues: [{ summary: "The NFPA citation prints 6.4.1 where the section header is 5.4.1.", excerpt: "Reference: NFPA 1072, 6.4.1 (A- 3) (B- 1,2), 4.3.1 (A- 1-3) (B- 1.2.3.8)", correction: "Confirm the NFPA section against the printed key." }],
      r: [{ t: "6.4.1 (A-3) (B-1, 2) [as printed; header is 5.4.1], 4.3.1 (A-1-3) (B-1, 2, 3, 5).", x: true }, "page 346.", "page 139."],
      o: "70. When sheltering people in place, the citizens should be directed to: A. close all heating, ventilation, and air-conditioning systems. B. open windows for air exchange. C. keep all heating, ventilation, and air-conditioning systems running. D. periodically open the doors to relieve the pressure." }),
    rec({ n: 71, key: "71. 5.4.1 ACT PLAN IMPLE 28",
      q: "The person who advises the Incident Commander of existing or potentially unsafe conditions and monitors conditions of personnel is the:",
      c: ["Operations Officer.", "Safety Officer.", "Recon Officer.", "Team Leader."], a: "B",
      r: ["5.4.1 (A-6(a, b, c, d)).", "page 323. Fig. 7.2.", "page 145."],
      o: "71. The person who advises the Incident Commander of existing or potentiaily unsafe conditions and monitors conditions of personnel is the: A. Operations Officer. B. Safety Officer. C. Recon Officer. D. Team Leader." }),
    rec({ n: 72, key: "72. 5.4.1 ACT PLAN IMPLE 45",
      q: "Heat exhaustion is associated with:",
      c: ["cold", "cold and clammy skin.", "muscle cramps in legs and abdomen.", "state of unconsciousness."], a: "B",
      status: "needs_review",
      issues: [{ summary: "Choice A is printed as the single word \"cold\" and may be truncated.", excerpt: "A. cold / B. cold and clammy skin.", correction: "Confirm choice A against the printed page." }],
      r: ["5.4.1 (A-8, 9), 6.2.1 (A-3).", "page 554.", "page 142."],
      o: "72. Heat exhaustion is associated with: A. cold B. cold and clammy skin. C. muscle cramps in legs and abdomen. D. state of unconsciousness." }),
    rec({ n: 73, key: "73. 5.4.1 ACT PLAN IMPLE 46",
      q: "Which is a true life-threatening emergency that requires immediate attention?",
      c: ["Heat exhaustion", "Heat stroke", "Heat stress", "Heat cramps"], a: "B",
      r: ["5.4.1 (A-8, 9).", "page 455.", "page 142."],
      o: "73. Which is a true life-threatening emergency that requires immediate attention? A. Heat exhaustion B. Heat stroke C. Heat stress D. Heat cramps" }),
    rec({ n: 74, key: "74. 5.5.1 EMERG DECON 3",
      q: "Which is correct regarding emergency decontamination?",
      c: ["It must take place in the decontamination corridor.", "There must be environmental protection in place.", "The property must be protected first.", "It is required when immediate medical attention is necessary."], a: "D",
      r: ["5.5.1 (A-4, 5) (B-1, 4), 5.3.1 (A-18, 19) (B-3).", "page 314.", "pages 124, 210."],
      o: "74. Which is correct regarding emergency decontamination? A. It must take place in the decontamination corridor. B. There must be environmental protection in place. C. The property must be protected first. D. It is required when immediate medical attention is necessary." }),
    rec({ n: 75, key: "75. 6.2.1 PERS PROT EQUI 3",
      q: "What would be the result of allowing a contaminated individual to leave the hot zone without being decontaminated?",
      c: ["Nothing. All contaminates would be gone after the individual exited the hot zone.", "The contaminates would be transferred to other personnel or equipment.", "The individual would be treated for exposure but is no risk to others.", "There would be direct contamination of the warm zone."], a: "B",
      r: ["6.2.1 (A-1, 3) (B-2).", "page 479.", "page 126."],
      o: "75. What would be the result of allowing a contaminated individual to leave the hot zone without being decontaminated? A. Nothing. All contaminates would be gone after the individual exited the hot zone. B. The contaminates would be transferred to other personnel or equipment. C. The individual would be treated for exposure but is no risk to others. D. There would be direct contamination of the warm zone." })
  ];

  var meta = {
    id: "awareness-i3",
    sourceId: bank.sourceId,
    title: "Hazardous Materials Awareness — Examination I-3",
    shortLabel: "Examination I-3",
    level: "awareness",
    keyAppendix: "Appendix A",
    itemCount: 75,
    answerNote: "Answer letters and citations come from the Examination I-3 key in Appendix A. They have not been independently verified.",
    readingList: [
      "IFSTA, Hazardous Materials for First Responders, 5th Edition, Chapters 1, 2, 3, 6, 7, and 14.",
      "Jones and Bartlett Learning, Hazardous Materials Awareness and Operations, 3rd Ed, Chapters 1–6, 11, and 12."
    ],
    directions: "Examination I-3 has 75 items. The book says to remove it from the manual, take it in a quiet place without interruptions, and follow the Phase III time-management directions. Mark one answer, A–D, mark guesses, score the exam from the key, then review missed and guessed items.",
    sourceNotes: [
      "The printed directions say \"There should be 100 exam items\", but the exam ends at question 75 and the key has 75 entries. No records were invented for the missing 25.",
      "Key entry 4 has no answer line and key entry 14's answer is unreadable; both questions are held for review.",
      "Questions 32 and 33 depend on placard drawings that are not in the scan.",
      "Questions 4 and 47 are printed as unlabeled choice columns; their A–D letters cannot be confirmed from the scan."
    ]
  };

  bank.register(questions, meta);
})();
