/**
 * Hazardous Materials Awareness — Examination I-2
 *
 * Source: PTS Publications exam prep, Seventh Edition 2022, printed pages
 * 24–33. Answers and citations come from the Examination I-2 key in
 * Appendix A (printed pages 127–136), matched by question number.
 * Answers are source-provided and have not been independently verified.
 */
(function () {
  "use strict";

  var bank = globalThis.ExamPrepBank.createExam({
    examId: "awareness-i2",
    examLabel: "Hazardous Materials Awareness — Examination I-2",
    shortLabel: "Examination I-2",
    level: "awareness",
    idPrefix: "exam-i2"
  });
  var rec = bank.rec;
  var U = { t: "page unreadable.", x: true };
  var BLANK = "A fill-in blank was restored where the OCR dropped the printed underline.";

  function blankIssue(excerpt) {
    return { summary: "The printed fill-in blank was dropped by the OCR.", excerpt: excerpt, correction: "Confirm the blank position against the printed page." };
  }

  var questions = [
    rec({ n: 1, key: "1. 5.2.1 ID POT HAZARD 87",
      q: "The products that IM 101 intermodal portable tanks typically carry are:",
      c: ["molten sulfur.", "flammable gases.", "flammable liquids.", "radioactive materials."], a: "C",
      r: ["5.2.1 (A-2, 3) (B-1).", "pages 266-267. Table 5.7, Table 5.8.", "pages 73, 76. Fig. 4-5."],
      notes: ["The key prints this entry's number as \"4.\"; it is the first Examination I-2 key entry and is matched to question 1."],
      o: "1. The products that IM 101 intermodal portabie tanks typically carry are: A. molten sulfur. B. flammable gases. C. flammable liquids. D. radioactive materials," }),
    rec({ n: 2, key: "2. 5.2.1 ID POT HAZARD 88",
      q: "The products that IM 102 intermodal portable tanks typically carry are:",
      c: ["nonregulated materials.", "flammable gases.", "hydrogen.", "radioactive materials."], a: "A",
      r: ["5.2.1 (A-2, 3) (B-1).", "pages 266-267. Table 5.7, Table 5.8.", "pages 74, 76. Fig. 4-5."],
      o: "2. The products that IM 102 intermodal portable tanks typically carry are: A. nonregulated materials. B. flammable gases. C. hydrogen. D. radioactive materials," }),
    rec({ n: 3, key: "3. 5.2.1 ID POT HAZARD 89",
      q: "The item that is represented by the vertical stripes indicates the:",
      c: ["radioactive levels.", "Hazard Class.", "maximum radiation levels.", "number of radioactive atoms."], a: "A", hold: true,
      image: "Radioactive label drawing with vertical stripes; the OCR caption reads \"Top half Background is Yellow / Bottom half Background is white\". The scan does not include the drawing.",
      issues: [{ summary: "The question depends on a label illustration that is not in the scan.", excerpt: "The item that is represented by the vertical stripes indicates the: C Top half ., Background 9. Whe is Yellow Bottorn half . Background is white", correction: "Add the radioactive label illustration (IFSTA Fig. 4.76 / Jones and Bartlett Fig. 4-42) before scoring." }],
      r: ["5.2.1 (A-3, 8(j)) (B-1, 5).", "pages 194, 195. Fig. 4.76.", "pages 95, 96. Fig. 4-42."],
      o: "3. The item that is represented by the vertical stripes indicates the: C Top half ., Background 9. Whe is Yellow Bottorn half . Background is white A. radioactive levels. B. Hazard Class. C. maximum radiation levels. D. number of radioactive atoms." }),
    rec({ n: 4, key: "4. 5.2.1 ID POT HAZARD 90",
      q: "The design pressure of an IM 101 portable tank is:",
      c: ["14.5 to 25.4 psi.", "100 to 500 psi.", "25.4 to 100 psi.", "6.89 to 14.5 psi."], a: "C",
      r: ["5.2.1 (A-2) (B-1).", "page 267. Table 5.8.", "pages 73, 74, 76. Fig. 4-5."],
      o: "4. The design pressure of an IM 101 portable tank is: hazz A. 14.5 to 25.4 psi. B. 100 to 500 psi. C. 25.4 to 100 psi. D. 6.89 to 14.5 psi." }),
    rec({ n: 5, key: "5. 5.2.1 ID POT HAZARD 93",
      q: "What type of container is used to ship materials of radioactivity by air?",
      c: ["Industrial", "Type A", "Type C", "Extruded"], a: "C",
      r: ["5.2.1 (A-2, 3, 8(i)) (B-1).", "page 96.", "page 97. Fig. 4-45."],
      o: "5. What type of container is used to ship materials of radioactivity by air? A. Industrial B. Type A C. Type C D. Extruded" }),
    rec({ n: 6, key: "6. 5.2.1 ID POT HAZARD 94",
      q: "Packaging used for transport with extremely low levels of radioactivity that present no risk to the public or environment is:",
      c: ["Type", "Excepted.", "Concrete Box.", "Industrial."], a: "B", hold: true,
      issues: [{ summary: "Choice A is truncated in the scan (\"Type\" with no type letter).", excerpt: "A. Type", correction: "Restore the full text of choice A from the printed page." },
        { summary: "The NFPA citation is garbled.", excerpt: "NEPA 1072, 5.2.1 (A- 2,3, - 1).", correction: "Restore the NFPA 1072 subsections from the key." }],
      r: [{ t: "5.2.1 (A-2, 3, [unreadable] -1).", x: true }, "page 273.", "page 97."],
      origCite: "Ref * NEPA 1072, 5.2.1 (A- 2,3, - 1).",
      o: "6. Packaging used for transport with extremely low levels of radioactivity that present no risk to the public or environment is: A. Type B. Excepted. C. Concrete Box. D. Industrial." }),
    rec({ n: 7, key: "7. 5.2.1 ID POT HAZARD 95",
      q: "Which material is transported in industrial containers?",
      c: ["High level radiation", "Natural uranium", "Plutonium", "Smoke detectors"], a: "D",
      r: ["5.2.1 (A-2, 8(j)) (B-2).", "page 67.", "page 97."],
      o: "7. Which material is transported in industrial containers? A. High level radiation B. Natural uranium C. Plutonium D. Smoke detectors" }),
    rec({ n: 8, key: "8. 5.2.1 ID POT HAZARD 100",
      q: "IBCs are:",
      c: ["intermodal bulk containers.", "intermediate bulk containers.", "international bulk containers.", "intermediate biological containers."], a: "B",
      r: ["5.2.1 (A-2) (B-1).", "page 277.", "page 76."],
      o: "8. IBCs are: A. intermodal bulk containers. B. intermediate bulk containers. C. international bulk containers. D. intermediate biological containers." }),
    rec({ n: 9, key: "9. 5.2.1 ID POT HAZARD 102",
      q: "Where would you find valves on a one-ton container?",
      c: ["End", "Top", "Bottom", "Middle"], a: null, hold: true,
      issues: [{ summary: "The key entry for question 9 has no answer line in the scan.", excerpt: "Jones and Bartlett ... pages 73- 74, Fj / 10. 5.2.1 ID POT HAZARD 104", correction: "Restore the answer letter from the printed key, page 128." }],
      r: ["5.2.1 (A-2) (B-1).", "page 272. Fig. 5.93.", { t: "pages 73-74. Fig. [unreadable].", x: true }],
      o: "9. Where would you find valves on a one-ton container? A. End B. Top C. Bottom D. Middle" }),
    rec({ n: 10, key: "10. 5.2.1 ID POT HAZARD 104",
      q: "Emergency centers such as the _____ are principal agencies providing immediate technical assistance to an emergency responder.",
      c: ["Occupational Safety and Health Administration", "National Fire Protection Association", "National Center for Disease Control", "CHEMTREC®"], a: "D",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("Emergency centers such as the are principal agencies")],
      r: ["5.2.1 (A-6(a)) (B-5), 5.3.1 (A-1, 7, 10), 4.3.1 (A-1), 4.4.1 (A-2) (B-2).", "page 204.", "page 82."],
      o: "10. Emergency centers such as the are principal agencies providing immediate technical assistance to an emergency responder. A. Occupational Safety and Health Administration B. National Fire Protection Association C. National Center for Disease Control D. CHEMTREC®" }),
    rec({ n: 11, key: "11. 5.2.1 ID POT HAZARD 105",
      q: "Cryogenic liquids are those which exist at:",
      c: ["greater than 32°F.", "minus 0°F.", "minus 130°F.", "minus 110°F."], a: "C",
      notes: ["Choice B is printed as \"minus O°F\" in the scan; the letter O was read as the digit 0."],
      r: ["5.2.1 (A-8(f)).", "page 255.", "page 44."],
      o: "11. Cryogenic liquids are those which exist at: A. greater than 32°F. . B. minus O°F. C. minus 130°F. D. minus 110°F." }),
    rec({ n: 12, key: "12. 5.2.1 ID POT HAZARD 106",
      q: "A substance that spontaneously releases ionizing radiation would be labeled hazard classification _____.",
      c: ["7", "9", "11", "13"], a: "A",
      status: "needs_review", notes: ["The choices are scattered around the stem in the scan (\"A. 7\" appears above the question); the A–D order was taken from the printed letters.", BLANK],
      issues: [{ summary: "Choice layout is scrambled in the scan.", excerpt: "A. 7 / 12. A substance that spontaneous!y releases ionizing radiation would be labeled hazard classification / B. 9 Cc. 11 / D. 13", correction: "Confirm the choice order and the blank against the printed page." },
        { summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A- 1,3,8())) (B- 2).", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-1, 3, 8([unreadable])) (B-2).", x: true }, "pages 76, 78, 85. Fig. 2.37, Fig. 2.49, Table 2.5.", "pages 34-35, 38. Fig. 2-25."],
      o: "A. 7 12. A substance that spontaneous!y releases ionizing radiation would be labeled hazard classification B. 9 Cc. 11 D. 13" }),
    rec({ n: 13, key: "13. 5.2.1 ID POT HAZARD 107",
      q: "Which value represents an atmosphere that poses an immediate hazard to life or can cause irreversible, debilitating effects on health?",
      c: ["TLV-TWA", "IDLH", "REL", "PEL"], a: "B",
      r: ["5.2.1 (A-12) (B-8).", "pages 423, 534. Table 11.1.", "pages 107, 166."],
      o: "13. Which value represents an atmosphere that poses an immediate hazard to life or can cause irreversible, debilitating effects on health? A. TLV-TWA B. IDLH C. REL D. PEL" }),
    rec({ n: 14, key: "14. 5.2.1 ID POT HAZARD 110",
      q: "Beta particles are:",
      c: ["having weight and mass.", "ionizing radiation like X-rays.", "deadly radiation.", "large particles that easily pass-through protective gear."], a: "B",
      status: "needs_review",
      issues: [{ summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A- &()).", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, "page 534. Table 11.1.", "page 61."],
      o: "14. Beta particles are: A. having weight and mass. B. ionizing radiation like X-rays. C. deadly radiation. D. large particles that easily pass-through protective gear." }),
    rec({ n: 15, key: "15. 5.2.1 ID POT HAZARD 115",
      q: "Which type of radiation has a physical mass but has no electrical charge?",
      c: ["Beta", "Gamma", "X-ray", "Neutron"], a: "D",
      status: "needs_review",
      issues: [{ summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A- 8())).", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, "page 165.", "page 61."],
      o: "15. Which type of radiation has a physical mass but has no electrical charge? A. Beta B. Gamma C. X-ray D. Neutron" }),
    rec({ n: 16, key: "16. 5.2.1 ID POT HAZARD 116",
      q: "When contacting the Chemical Transportation Emergency Center, the caller should be prepared to provide the:",
      c: ["name of the site manager at the facility.", "type of container or vehicle.", "names of the responders.", "number of casualties."], a: "B",
      notes: ["\"Sho ' be\" in the scan was read as \"should be\"."],
      r: ["5.2.1 (A-4, 6(a)) (B-5), 5.3.1 (A-1, 10), 4.4.1 (A-1) (B-2).", "page 204.", "page 82."],
      o: "16. When contacting the Chemical Transportation Emergency Center, the caller Sho ‘ be prepared to provide the: A. name of the site manager at the facility. B. type of container or vehicle. C. names of the responders. D. number of casualties." }),
    rec({ n: 17, key: "17. 5.2.1 ID POT HAZARD 117",
      q: "The Chemical Transportation Emergency Center can aid responders if:",
      c: ["they have a Safety Data Sheet to fax.", "they have received financial authorization for clean-up.", "the name of the shipper or manufacturer is known.", "they are the approved hazardous materials team."], a: "C",
      r: ["5.2.1 (A-4, 6(a)) (B-5), 5.3.1 (A-1, 10).", "page 204.", "page 82."],
      o: "17. The Chemical Transportation Emergency Center can aid responders if: A. they have a Safety Data Sheet to fax. B. they have received financial authorization for clean-up. C. the name of the shipper or manufacturer Is known. D. they are the approved hazardous materials team." }),
    rec({ n: 18, key: "18. 5.2.1 ID POT HAZARD 118",
      q: "The Chemical Transportation Emergency Center and the Canadian Transport Emergency Centre can usually provide:",
      c: ["authorization for cleanup.", "previous incidents and exposures.", "technical information.", "advice on remediation contractors."], a: "C",
      r: ["5.2.1 (A-4, 6(a)) (B-5), 5.3.1 (A-1, 10).", "page 205.", "page 82."],
      o: "18. The Chemical Transportation Emergency Center and the Canadian Transport Emergency Centre can usually provide: A. authorization for cleanup. B. previous incidents and exposures. C. technical information. D. advice on remediation contractors" }),
    rec({ n: 19, key: "19. 5.2.1 ID POT HAZARD 119",
      q: "In an emergency at a facility with bulk chemical storage, where the Safety Data Sheet is not available on site, the firefighter may obtain information from:",
      c: ["an Environmental Protection Association Alert.", "the chemical abstract services.", "the Department of Transportation.", "the Chemical Transportation Emergency Center."], a: "D",
      notes: ["Choice names were kept as printed. Examination I-1 question 75 is a close paraphrase with \"CHEMTREC®\" as choice D."],
      r: ["5.2.1 (A-4, 5, 6(a)) (B-5), 5.3.1 (A-1, 7, 10).", "page 204.", "page 82."],
      o: "19. In an emergency at a facility with bulk chemical storage, where the Safety Data Sheet is not available on site, the firefighter may obtain information from: A. an Environmental Protection Association Alert. B. the chemical abstract services. C. the Department of Transportation. D. the Chemical Transportation Emergency Center." }),
    rec({ n: 20, key: "20. 5.2.1 ID POT HAZARD 120",
      q: "What would be the major concern if you were to come upon a leaking tanker of the type pictured below?",
      c: ["Frost bite", "Ignition of vapors", "Encountering corrosives", "Encountering bulk solids"], a: "C", hold: true,
      image: "Cargo tank truck photograph referenced by the stem (\"pictured below\"); the key cites IFSTA Fig. 5.5 and Jones and Bartlett Fig. 4-16. The scan does not include the picture.",
      issues: [{ summary: "The question depends on a tanker picture that is not in the scan.", excerpt: "a leaking tanker of the type pictured below?", correction: "Add the tanker picture before scoring." }],
      r: ["5.2.1 (A-2) (B-1).", "page 249. Fig. 5.5.", "page 78. Fig. 4-16."],
      o: "20. What would be the major concern if you were to come upon a leaking tanker of the type pictured below? A. Frost bite B. Ignition of vapors C. Encountering corrosives D. Encountering bulk solids" }),
    rec({ n: 21, key: "21. 5.2.1 ID POT HAZARD 121",
      q: "Radiation that can be stopped by a piece of paper consists of _____ particles.",
      c: ["alpha", "beta", "neutron", "gamma"], a: "A",
      status: "needs_review", notes: [BLANK, "Choice C is printed \"neuron\" in the scan and was read as \"neutron\"."],
      issues: [blankIssue("Radiation that can be stopped by a piece of paper consists of particles."),
        { summary: "The NFPA citation sub-item is unreadable.", excerpt: "5.2.1 (A-8()", correction: "Restore the 8( ) sub-item from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, "page 64.", "page 61. Fig. 3-17."],
      o: "21. Radiation that can be stopped by a piece of paper consists of particles. wan i A. alpha B. beta C. neuron D. gamma po" }),
    rec({ n: 22, key: "22. 5.2.1 ID POT HAZARD 122",
      q: "The radiation that is least dangerous as a threat to external portions of the body but is dangerous if ingested or inhaled is:",
      c: ["alpha.", "ultraviolet.", "electromagnetic.", "gamma."], a: "A",
      status: "needs_review",
      issues: [{ summary: "The key header and citation for this entry are garbled.", excerpt: "22. 5.2.11D POT HAZAR' an 30. Reference: NFPA 1072, 6.2.1 (A-8(/). dition, pages 163-164 ... 3rd Ed, page 61. Fig. 3.47", correction: "Confirm the reference number (read as 122) and the NFPA subsection from the printed key, page 130." }],
      r: [{ t: "6.2.1 (A-8([unreadable])) as printed; likely 5.2.1.", x: true }, "pages 163-164.", "page 61. Fig. 3.47."],
      origCite: "Reference: NFPA 1072, 6.2.1 (A-8(/). dition, pages 163-164, pete! IFSTA, terials for First Responders, 5th Edition, ; T donee arg barter oeanious Materials Awareness and Operations, 3rd Ed, page 61. Fig. 3.47",
      o: "22. The radiation that is least dangerous as a threat to external portions of the body but is dangerous if ingested or inhaled is: } A. alpha. B. ultraviolet. ma C. electromagnetic. D. gamma." }),
    rec({ n: 23, key: "23. 5.2.1 ID POT HAZARD 123",
      q: "_____ rays are the most dangerous type of radiation.",
      c: ["Alpha", "Beta", "Neutron", "Gamma"], a: "D",
      status: "needs_review", notes: [BLANK],
      issues: [blankIssue("23. rays are the most dangerous type of radiation."),
        { summary: "Both textbook page citations are garbled.", excerpt: "5th Edition, page 1 $5. Ed, page 62 Res / 3rd Ed, ' pages 29-30. Fig. 2.", correction: "Restore the IFSTA and Jones and Bartlett pages from the key." }],
      r: [{ t: "5.2.1 (A-8([unreadable])).", x: true }, U, { t: "pages 29-30 (partly unreadable). Fig. 2-[unreadable].", x: true }],
      o: "23. rays are the most dangerous type of radiation. A. Alpha B. Beta C. Neutron D. Gamma" }),
    rec({ n: 24, key: "24. 5.2.1 ID POT HAZARD 124",
      q: "Caustic sodium hydroxide and potassium hydroxide are examples of:",
      c: ["polymers.", "catalysts.", "acids.", "bases."], a: "D",
      status: "needs_review",
      issues: [{ summary: "The Jones and Bartlett page is unreadable.", excerpt: "3r 1 Pag » Fig. 3-15", correction: "Restore the page from the key." }],
      r: ["5.2.1 (A-8(c)).", "page 157.", { t: "page unreadable. Fig. 3-15.", x: true }],
      o: "24. Caustic sodium hydroxide and potassium hydroxide are examples of: A. polymers. B. catalysts. C. acids. D. bases." }),
    rec({ n: 25, key: "25. 5.2.1 ID POT HAZARD 125",
      q: "Chemicals that ignite when combined create _____ reaction.",
      c: ["a hyperbolic", "an exothermic", "a congenial", "a cryogenic"], a: "B",
      status: "needs_review", notes: [BLANK, "Choice A is printed \"hyperbolic\" and was kept as printed."],
      issues: [blankIssue("Chemicals that ignite when combined create reaction."),
        { summary: "Both textbook page citations are unreadable.", excerpt: "5th Edition, page d Fd 59. Fi 1 / 3r 1 page oy. Fig. 3.145", correction: "Restore the pages from the key." }],
      r: ["5.2.1 (A-8(b)).", U, { t: "page unreadable. Fig. 3-14 [as printed \"3.145\"].", x: true }],
      o: "25. Chemicals that ignite when combined create reaction. A. a hyperbolic B. an exothermic C. a congenial D. a cryogenic" }),
    rec({ n: 26, key: "26. 5.2.1 ID POT HAZARD 130",
      q: "Responders can contact the shipper directly from the emergency contact information on the:",
      c: ["Safety Data Sheet.", "Pre-Incident Plan.", "shipping papers.", "Chemical Abstract Service."], a: "C",
      status: "needs_review",
      issues: [{ summary: "A second NFPA section in the citation lost its leading digit.", excerpt: "(B- 5). .3.1 (A- 1,8).", correction: "Restore the section number (likely 5.3.1) from the key." }],
      r: [{ t: "5.2.1 (A-5, 6(b, c, d), 7) (B-5), [?].3.1 (A-1, 8).", x: true }, "page 99.", "pages 29-30. Fig. 2-18."],
      o: "26. Responders can contact the shipper directly from the emergency contact information on the: A. Safety Data Sheet. B. Pre-Incident Plan. C. shipping papers. D. Chemical Abstract Service." }),
    rec({ n: 27, key: "27. 5.2.1 ID POT HAZARD 131",
      q: "A _____ is a release that is the result of a broken or damaged valve(s) that may last from several seconds to several minutes, depending on the size of the opening, type of container, and nature of contents.",
      c: ["spill", "detonation", "rapid relief", "violent rupture"], a: "C",
      status: "needs_review", notes: [BLANK],
      issues: [blankIssue("27.A is a release that is the result of a broken or damaged valve(s)")],
      r: ["5.2.1 (A-1, 2, 8(n)).", "page 218.", "page 23."],
      o: "27.A is a release that is the result of a broken or damaged valve(s) that may last from several seconds to several minutes, depending on the size Boo: of the opening, type of container, and nature of contents. A. spill B. detonation C. rapid relief D. violent rupture" }),
    rec({ n: 28, key: "28. 5.2.1 ID POT HAZARD 133",
      q: "_____ materials may cause severe chemical burns and extensive tissue damage.",
      c: ["Corrosive", "Radioactive", "Carcinogenic", "Etiologic"], a: "A",
      status: "needs_review", notes: [BLANK],
      issues: [blankIssue("28. materials may cause severe chemical burns and extensive tissue damage."),
        { summary: "The Jones and Bartlett page is unreadable.", excerpt: "3rd Ed, page T12FSTA", correction: "Restore the page from the key." }],
      r: ["5.2.1 (A-8(c), 12).", "page 27.", U],
      o: "28. materials may cause severe chemical burns and extensive tissue 3 ao damage. A. Corrosive B. Radioactive C. Carcinogenic D. Etiologic" }),
    rec({ n: 29, key: "29. 5.2.1 ID POT HAZARD 135",
      q: "Which substance would be classified as a chemical asphyxiant?",
      c: ["Carbon dioxide", "Nitrogen", "Hydrogen cyanide", "Methane"], a: "C",
      r: ["5.2.1 (A-8(m, n)).", "page 395.", "page 182."],
      o: "29. Which substance would be classified as a chemical asphyxiant? A. Carbon dioxide B. Nitrogen C. Hydrogen cyanide D. Methane" }),
    rec({ n: 30, key: "30. 5.2.1 ID POT HAZARD 136",
      q: "Vapors that attack the mucous membranes, such as the surfaces of the eyes, nose and throat, are considered:",
      c: ["asphyxiants.", "irritants.", "anesthetics.", "carcinogens."], a: "B",
      status: "needs_review",
      issues: [{ summary: "The IFSTA page is missing from the citation.", excerpt: "IFSTA, Hazardous Materials for First Responders, 5th Edith", correction: "Restore the IFSTA page from the key." }],
      r: ["5.2.1 (A-8(m, n)).", { t: "page missing.", x: true }, "page 69."],
      o: "30. Vapors that attack the mucous membranes, such as the surfaces of the eyes, nose and throat, are considered: A. asphyxiants. B. irritants. C. anesthetics. D. carcinogens." }),
    rec({ n: 31, key: "31. 5.2.1 ID POT HAZARD 137",
      q: "_____ interfere with oxygen exchange during normal respiration.",
      c: ["Anesthetics", "Carcinogens", "Irritants", "Asphyxiants"], a: "D",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("31. interfere with oxygen exchange during normal respiration.")],
      r: ["5.2.1 (A-8(m, n)).", "page 172.", "page 42."],
      o: "31. interfere with oxygen exchange during normal respiration. A. Anesthetics B. Carcinogens C. Irritants D. Asphyxiants:" }),
    rec({ n: 32, key: "32. 5.2.1 ID POT HAZARD 138",
      q: "Materials such as lithium, finely divided magnesium, sodium, and cesium are classified as:",
      c: ["hypergolic.", "pyrophoric.", "water reactive.", "inhibitors."], a: "C",
      r: ["5.2.1 (A-8(m)).", "page 198.", "page 58."],
      o: "32. Materials such as lithium, finely divided magnesium, sodium, and cesium are classified as: A. hypergolic. B. pyrophoric. C. water reactive. D. inhibitors." }),
    rec({ n: 33, key: "33. 5.2.1 ID POT HAZARD 139",
      q: "_____ is the difference between the upper and lower flammable limits of a gas or vapor.",
      c: ["Flash point", "Ignition temperature", "Flammable/explosive range", "Vapor density"], a: "C",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("33. is the difference between the upper and lower flammabie limits of a gas or vapor.")],
      r: ["5.2.1 (A-8(d, e)).", "page 156.", "page 54."],
      o: "33. is the difference between the upper and lower flammabie limits of a gas or vapor. A. Flash point B. Ignition temperature C. Flammabie/explosive range D. Vapor density" }),
    rec({ n: 34, key: "34. 5.2.1 ID POT HAZARD 140",
      q: "A corrosive is:",
      c: ["an effect of acids and bases on a metal.", "a substance's tendency to deteriorate another substance.", "the percentage of an acid or base dissolved in water.", "a degree a substance will mix with water."], a: "B",
      r: ["5.2.1 (A-8(c)).", "pages 157-158.", "page 58."],
      o: "34. A corrosive is: A. an effect of acids and bases on a metal. B. a substance's tendency to deteriorate another substance. C. the percentage of an acid or base dissolved in water. D. a degree a substance will mix with water." }),
    rec({ n: 35, key: "35. 5.2.1 ID POT HAZARD 145",
      q: "Determining whether a vapor will rise, or fall is:",
      c: ["vapor dispersion.", "vapor density.", "vaporization.", "specific gravity."], a: "B",
      r: ["5.2.1 (A-8(m)).", "pages 148-149.", "page 56."],
      o: "35. Determining whether a vapor will rise, or fall is: A. vapor dispersion. B. vapor density. C. vaporization. D. specific gravity." }),
    rec({ n: 36, key: "36. 5.2.1 ID POT HAZARD 147",
      q: "Chemicals that are classified as _____ can cause a severe allergic reaction.",
      c: ["asphyxiants", "sensitizers", "irritants", "convulsants"], a: null, hold: true,
      notes: [BLANK],
      issues: [{ summary: "The key entry for question 36 has no answer line in the scan.", excerpt: "36. 5.2.1 ID POT HAZARD 147 ... 3rd Ed, page 63. / 37. 5.2.1 ID POT HAZARD 148", correction: "Restore the answer letter from the printed key, page 131." }],
      r: ["5.2.1 (A-1, 8(n)).", "page 173.", "page 63."],
      o: "36. Chemicals that are classified as can cause a severe allergic reaction. A. asphyxiants B. sensitizers C. irritants D. convulsants" }),
    rec({ n: 37, key: "37. 5.2.1 ID POT HAZARD 148",
      q: "Toxic gases would fall under which UN/DOT hazard class and division?",
      c: ["1.1", "1.2", "6.1", "2.3"], a: "D",
      r: ["5.2.1 (A-1).", "pages 76, 78, 83. Fig. 2.37, Fig. 2.40, Table 2.5.", "page 37."],
      o: "37. Toxic gases would fall under which UN/DOT hazard class and division? A. 1.1 B. 1.2 C. 6.1 D. 2.3" }),
    rec({ n: 38, key: "38. 5.2.1 ID POT HAZARD 149",
      q: "Which is considered a Department of Transportation Hazard Class 4 product?",
      c: ["Flammable gas", "Flammable solid", "Oxidizing substances", "Flammable liquid"], a: "B",
      notes: ["Choices B–D are printed on one line in the scan; the letters are legible."],
      r: ["5.2.1 (A-1).", "pages 76, 78, 83. Fig. 2.37, Fig. 2.40, Table 2.6 [as printed].", "page 37."],
      o: "38. Which is considered a Department of Transportation Hazard Class 4 product? A. Flammable gas B. Flammable solid c. Oxidizing substances D. Flammable liquid" }),
    rec({ n: 39, key: "39. 5.2.1 ID POT HAZARD 150",
      q: "One type of hazardous material that is classified as Department of Transportation Hazard Class 1.1 is:",
      c: ["spontaneously combustible materials.", "water reactive substances.", "oxidizing substances.", "explosives with a mass explosion hazard."], a: "D",
      r: ["5.2.1 (A-1).", "pages 76, 78, 83. Fig. 2.37, Fig. 2.40.", "page 37."],
      o: "39. One type of hazardous material that is classified as Department of Transportation Hazard Class 1.1 is: A. spontaneously combustible materials. B. water reactive substances. C. oxidizing substances. D. explosives with a mass explosion hazard." }),
    rec({ n: 40, key: "40. 5.2.1 ID POT HAZARD 151",
      q: "The minimum temperature at which a liquid gives off enough vapors to form an ignitable mixture, with air near the surface, is the:",
      c: ["combustion point", "ignition point", "flash point", "fire point"], a: "C",
      r: ["5.2.1 (A-8(e)).", "pages 154-155. Fig. 4.29.", "page 53."],
      o: "40. The minimum temperature at which a liquid gives off enough vapors to form an ignitable mixture, with air near the surface, is the: A. combustion point ) B. ignition point C. flash point D. fire point" }),
    rec({ n: 41, key: "41. 5.2.1 ID POT HAZARD 152",
      q: "Vapor pressures of a substance at 100°F:",
      c: ["will remain the same substance at 68°F.", "always higher than the same substance at 68°F.", "will be lower than the same substance at 68°F.", "will change chemical composition."], a: "B",
      notes: ["Degree symbols were restored (\"100oF\", \"68oF\", \"680F\" in the scan)."],
      r: ["5.2.1 (A-8(m)).", "page 145.", "page 55."],
      o: "41. Vapor pressures of a substance at 100oF: A. will remain the same substance at 68oF. B. always higher than the same substance at 68oF. C. will be lower than the same substance at 680F. D. will change chemical composition." }),
    rec({ n: 42, key: "42. 5.2.1 ID POT HAZARD 153",
      q: "Which DOT Hazard Class covers nerve agents used in chemical warfare?",
      c: ["DOT 6.3", "DOT 6.1", "DOT 6.2", "DOT 5.2"], a: "B",
      r: ["5.2.1 (A-1, 10(a, b)).", "pages 76, 78, 83. Fig. 2.37, Fig. 2.40, Table 2.5.", "page 37."],
      o: "42. Which DOT Hazard Class covers nerve agents used in chemicat warfare? A. DOT 6.3 B. DOT 6.1 C. DOT 6.2 D. DOT 5.2" }),
    rec({ n: 43, key: "43. 5.2.1 ID POT HAZARD 155",
      q: "You respond to a Weapons of Mass Destruction event with victims with pinpoint pupils and twitchy muscles. You suspect they were exposed to a:",
      c: ["nerve agent.", "blister agent.", "blood agent.", "irritant agent."], a: "A",
      r: ["5.2.1 (A-10(a, b)).", "page 394. Table 8.4.", "page 92."],
      o: "43. You respond to a Weapons of Mass Destruction event with victims with pinpoint pupils and twitchy muscles. You suspect they were exposed to a: A. nerve agent. B. blister agent. C. blood agent. D. irritant agent." }),
    rec({ n: 44, key: "44. 5.2.1 ID POT HAZARD 162",
      q: "The primary hazard to responders rescuing victims in the vicinity of a fire involving products of Hazard Class 1 is:",
      c: ["inhalation.", "ingestion.", "injection.", "explosion."], a: "D",
      r: ["5.2.1 (A-1, 8(d, e)).", "page 178. Fig. 4-58.", "page 37."],
      o: "44. The primary hazard to responders rescuing victims in the vicinity of a fire involving products of Hazard Class 1 is: A. inhalation. B. ingestion. C. injection. D. explosion." }),
    rec({ n: 45, key: "45. 5.2.1 ID POT HAZARD 165",
      q: "The general routes of entry for human exposure to hazardous materials are:",
      c: ["inhalation, ingestion, radiation, and injection.", "injection, infection, radiation, and adsorption.", "inhalation, ingestion, absorption, and injection.", "absorption, dilution, injection, and ingestion."], a: "C",
      r: ["5.2.1 (A-4, 5, 8(a, h, i), 12) (B-8).", "pages 23-24. Fig. 1.9.", "page 40. Fig. 2-31."],
      o: "45. The general routes of entry for human exposure to hazardous materials are: A. inhalation, ingestion, radiation, and injection. B. injection, infection, radiation, and adsorption. C. inhalation, ingestion, absorption, and injection. D. absorption, dilution, injection, and ingestion." }),
    rec({ n: 46, key: "46. 5.2.1 ID POT HAZARD 167",
      q: "Pipeline-vent markers are required to state:",
      c: ["Poison control phone number", "Dates and times of pipeline activation", "Name and number for responding agency", "Product name, and phone number of owners."], a: "D",
      r: ["5.2.1 (A-3, 6(a-d), 12) (B-5).", "page 172.", "page 32."],
      o: "46. Pipeline-vent markers are required to state: A. Poison control phone number B. Dates and times of pipeline activation C. Name and number for responding agency D. Product name, and phone number of owners." }),
    rec({ n: 47, key: "47. 5.2.1 ID POT HAZARD 168",
      q: "Shippers of radioactive materials will display a placard that:",
      c: ["displays a number, the higher the number the more radiation is emitted.", "has a red and white striped background.", "lists the number for CHEMTREC.", "describes the level of personal protective equipment required to handle the materials."], a: "A",
      notes: ["Choice D is printed \"D: descrbes the level f personal protective equipment\" in the scan; the obvious spelling was cleaned."],
      r: ["5.2.1 (A-6(b-d), 7) (B-8).", "page 165.", "page 95."],
      o: "47. Shippers of radioactive materials will display a placard that: A. displays a number, the higher the number the more radiation is emitted. B. has a red and white striped background. C. lists the number for CHEMTREC. ; . D: descrbes the level f personal protective equipment required to handle the materials." }),
    rec({ n: 48, key: "48. 5.3.1 ID ACTION OPT 1",
      q: "_____ is the process of taking in materials through the skin or eyes.",
      c: ["Inhalation", "Absorption", "Injection", "Ingestion"], a: "B",
      status: "needs_review", notes: [BLANK, "The choices are printed on one line in the scan; the letters are legible."],
      issues: [blankIssue("48. is the process of taking in materials through the skin or eyes. _ A, Inhalation B. Absorption C. Injection D. Ingestion")],
      r: ["5.3.1 (A-15, 17).", "page 23.", "page 42."],
      o: "48. is the process of taking in materials through the skin or eyes. _ A, Inhalation B. Absorption C. Injection D. Ingestion" }),
    rec({ n: 49, key: "49. 5.3.1 ID ACTION OPT 2",
      q: "The route of exposure effecting the respiratory tracts associated with causing ill effects, both acute and chronic, is:",
      c: ["absorption.", "ingestion.", "inhalation.", "injection."], a: "C",
      r: ["5.3.1 (A-15, 17).", "page 23.", "page 40."],
      o: "49. _The route of exposure effecting the respiratory tracts associated with causing ill effects, both acute and chronic, is: A. absorption. B. ingestion. C. inhalation. D. injection." }),
    rec({ n: 50, key: "50. 5.3.1 ID ACTION OPT 7",
      q: "After repeated exposure, _____ will cause an allergic reaction.",
      c: ["carcinogens", "convulsants", "irritants", "sensitizers"], a: "D",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("50. After repeated exposure, will cause an allergic reaction.")],
      r: ["5.3.1 (A-15, 17).", "page 173.", "page 63."],
      o: "50. After repeated exposure, will cause an allergic reaction. A. carcinogens ; B. convulsants C. irritants D. sensitizers" }),
    rec({ n: 51, key: "51. 5.3.1 ID ACTION OPT 10",
      q: "Materials such as benzene, asbestos, and arsenic are:",
      c: ["corrosives.", "convulsants.", "irritants.", "carcinogens."], a: "D",
      r: ["5.3.1 (A-15, 17).", "page 173.", "pages 159, 59."],
      o: "51. Materials such as benzene, asbestos, and arsenic are: A. corrosives. B. convulsants. C. irritants. D. carcinogens." }),
    rec({ n: 52, key: "52. 5.3.1 ID ACTION OPT 11",
      q: "Which is a symptom of an irritant exposure?",
      c: ["Diarrhea", "Burning sensation to eyes", "Convulsions", "Fluid in lungs"], a: "B",
      r: ["5.3.1 (A-15).", "page 172.", "page 69."],
      o: "52. Which is a symptom of an irritant exposure? A. Diarrhea B. Burning sensation to eyes C. Convulsions D. Fluid in lungs" }),
    rec({ n: 53, key: "53. 5.3.1 ID ACTION OPT 13",
      q: "One of the most common products of combustion encountered in structure fires is:",
      c: ["Benzene.", "carbon monoxide.", "Hydrogen Chloride.", "Sulfur Dioxide."], a: "B",
      r: ["5.3.1 (A-15).", "page 174.", "page 160."],
      o: "53. One of the most common products of combustion encountered in structure fres is: A. Benzene. B. carbon monoxide. . C. Hydrogen Chloride. D. Sulfur Dioxide." }),
    rec({ n: 54, key: "54. 5.3.1 ID ACTION OPT 15",
      q: "A poison that can be harmful if inhaled, swallowed, absorbed, or introduced into the body is:",
      c: ["an asphyxiant.", "toxic.", "corrosive.", "a virus."], a: "B",
      r: ["5.3.1 (A-15, 17).", "page 36. Table 1.3.", "page 66."],
      o: "54. A poison that can be harmful if inhaled, swallowed, absorbed, or introduced este into the body is: A. an asphyxiant. B. toxic. C. corrosive. D. a virus." }),
    rec({ n: 55, key: "55. 5.3.1 ID ACTION OPT 22",
      q: "The resource that would be useful in determining the size of an endangered area during a hazmat incident is the:",
      c: ["International Fire Service Training Association Training Manual.", "National Fire Protection Association Guidebook.", "Emergency Response Guidebook.", "Environmental Protection Agency."], a: "C",
      r: ["5.3.1 (A-6).", "page 114.", "page 32."],
      o: "55. The resource that would be useful in determining the size of an endangered area during a hazmat incident is the: A. International Fire Service Training Association Training Manual. B. National Fire Protection Association Guidebook. C. Emergency Response Guidebook. D. Environmental Protection Agency." }),
    rec({ n: 56, key: "56. 5.3.1 ID ACTION OPT 31",
      q: "A process by which one substance combines with a second substance is:",
      c: ["absorption.", "mixture.", "combination.", "solution."], a: "A",
      r: ["5.3.1 (A-15, 17).", "page 489.", "page 212."],
      o: "56. A process by which one substance combines with a second substance is: A. absorption. B. mixture. C. combination. D. solution." }),
    rec({ n: 57, key: "57. 5.3.1 ID ACTION OPT 32",
      q: "A process by which a hazardous liquid flow is redirected away from an area is:",
      c: ["absorption", "dispersion", "diversion", "retention"], a: "C",
      r: ["5.3.1 (A-3) (B-1, 2), 5.4.1 (A-1) (B-1, 2).", "pages 614-615. Fig. 13.10.", "pages 272, 275. Skill Drill 12-6."],
      o: "57. A process by which a hazardous liquid flow is redirected away from an area is: A. absorption B. dispersion C. diversion D. retention" }),
    rec({ n: 58, key: "58. 5.4.1 ACT PLAN IMPLE 2",
      q: "The term shelter-in-place protection is:",
      c: ["keeping everyone not directly involved in the emergency operation away from the affected area.", "allowing only first responders into the affected area.", "moving everyone from a threatened area to a safer area.", "having people remain inside a building."], a: "D",
      status: "needs_review",
      issues: [{ summary: "The letter for choice B is missing in the scan; the text sits between choices A and C.", excerpt: "A. keeping everyone ... : / allowing only first responders into the affected area. / C. moving everyone", correction: "Confirm choice B against the printed page." }],
      r: ["5.4.1 (A-1, 3, 6(a-d)) (B-1, 2), 4.3.1 (A-2-3) (B-2).", "page 128.", "pages 110, 139."],
      o: "58. The term shelter-in-place protection is: A. keeping everyone not directly involved in the emergency operation away from the affected area. : allowing only first responders into the affected area. C. moving everyone from a threatened area to a safer area. D. having people remain inside a building." }),
    rec({ n: 59, key: "59. 5.4.1 ACT PLAN IMPLE 4",
      q: "Which is a potential ignition source found at the scenes of hazardous materials incidents?",
      c: ["Radios and flashlights", "Cylume sticks", "Contaminated water", "Inert gas"], a: "A",
      r: ["5.4.1 (A-1, 9) (B-1, 2).", "pages 201-202, 616. Fig. 4.85.", "page 135. Fig. 6-3."],
      o: "59. Which is a potential ignition source found at the scenes of hazardous materials incidents? A. Radios and flashlights B. Cylume sticks C. Contaminated water D. Inert gas" }),
    rec({ n: 60, key: "60. 5.4.1 ACT PLAN IMPLE 6",
      q: "The term evacuate is:",
      c: ["allowing only first responders into the affected area.", "having people remain inside a building rather than moving them to another area.", "moving everyone from a threatened area to a safer area.", "keeping everyone not directly involved in the emergency operation away from the affected area."], a: "C",
      r: ["5.4.1 (A-2) (B-1, 2), 4.3.1 (A-2-3) (B-4, 5).", "page 122.", "page 110."],
      o: "60. The term evacuate is: A. allowing only first responders into the affected area. B. having people remain inside a building rather than moving them to another area. C. moving everyone from a threatened area to a safer area. D. keeping everyone not directly involved in the emergency operation away from the affected area." }),
    rec({ n: 61, key: "61. 5.4.1 ACT PLAN IMPLE 14",
      q: "The zone where contamination has occurred or has the potential to occur, requires established entry, and exit control points is:",
      c: ["warm/contamination reduction zone.", "safety/cold zone.", "hot/exclusion zone.", "cold/support zone."], a: "C",
      r: ["5.4.1 (A-5) (B-3).", "pages 350, 363. Fig. 8.3.", "pages 137, 153."],
      o: "61. The zone where contamination has occurred or has the potential to occur, requires established entry, and exit control points is: A. warm/contamination reduction zone. B. safety/cold zone. C. hot/exclusion zone. D. cold/support zone." }),
    rec({ n: 62, key: "62. 5.4.1 ACT PLAN IMPLE 17",
      q: "One of the factors that can change the evacuation area is:",
      c: ["firefighters entering incidents from the north.", "a change in wind direction.", "the number of firefighters responding to the incident.", "the number of firefighters with self-contained breathing apparatus."], a: "B",
      r: ["5.4.1 (A-1) (B-1, 2), 4.3.1 (A-1-3) (B-1, 2, 3, 5).", "page 335. Fig. 7.13.", "page 138."],
      o: "62. One of the factors that can change the evacuation area is: A. firefighters entering incidents from the north. B. a change in wind direction. C. the number of firefighters responding to the incident. D. the number of firefighters with self-contained breathing apparatus." }),
    rec({ n: 63, key: "63. 5.4.1 ACT PLAN IMPLE 36",
      q: "The first step or most important thing to accomplish upon arrival at a hazardous materials or suspected hazardous materials incident is:",
      c: ["identification of the spilled or released product.", "victim recovery.", "notification of the hazardous materials response team.", "isolation of the area and prevention of entry."], a: "D",
      r: ["5.4.1 (A-1) (B-1, 2), 4.3.1 (A-2) (B-4).", "pages 120-121. Fig. 3.9.", "page 19."],
      o: "63.. .The first step or most important thing to accomplish upon arrival at a hazardous materials or suspected hazardous materials incident is: A. identification of the spilled or released product. B. victim recovery. C. notification of the hazardous materials response team. D. isolation of the area and prevention of entry." }),
    rec({ n: 64, key: "64. 5.5.1 EMERG DECON 2",
      q: "The goal of an emergency decontamination procedure is to:",
      c: ["completely remove all contamination while protecting the environment from run-off.", "remove any residual contamination after gross decontamination is completed.", "eliminate cross contamination of hospital personnel.", "quickly remove any threatening contamination."], a: "D",
      r: ["5.5.1 (A-5) (B-1).", "page 314.", "pages 124, 210."],
      o: "64. The goal of an emergency decontamination procedure is to: A. completely remove all contamination while protecting the environment from run-off. B. remove any residual contamination after gross decontamination is completed. C. eliminate cross contamination of hospital personnel. D. quickly remove any threatening contamination." }),
    rec({ n: 65, key: "65. 5.5.1 EMERG DECON 5",
      q: "The taking of hazardous materials into the body through the undamaged skin and the eyes are:",
      c: ["absorption.", "ingestion.", "inhalation.", "injection."], a: "A",
      r: ["5.5.1 (A-3), 5.3.1 (A-15, 17).", "page 23.", "page 42."],
      o: "65. The taking of hazardous materials into the body through the undamaged skin and the eyes are: A. absorption. B. ingestion. C. inhalation. D. injection." }),
    rec({ n: 66, key: "66. 5.5.1 EMERG DECON 6",
      q: "Which statement about emergency decontamination is true?",
      c: ["It can be implemented without a formal decontamination area.", "It provides only fine decontamination.", "The victim does not pose a threat of secondary contamination.", "It removes the threat of secondary decontamination."], a: "A",
      r: ["5.5.1 (A-4, 5) (B-1, 3).", "pages 314, 480.", "pages 124, 210."],
      o: "66. Which statement about emergency decontamination is true? A. It can be implemented without a formal decontamination area. B. It provides oniy fine decontamination. C. The victim does not pose a threat of secondary contamination. D. It removes the threat of secondary decontamination." }),
    rec({ n: 67, key: "67. 5.5.1 EMERG DECON 7",
      q: "_____ is designed to remove contaminates that pose immediate threat to life.",
      c: ["Emergency decontamination", "Secondary decontamination", "Decontamination", "Primary decontamination"], a: "A",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("67. is designed to remove contaminates that pose immediate threat to life,")],
      r: ["5.5.1 (A-4) (B-1), 6.4.1 (A-3-5) (B-2-4).", "pages 314, 480.", "pages 124, 210."],
      o: "67. is designed to remove contaminates that pose immediate threat to life, A. Emergency decontamination B. Secondary decontamination C. Decontamination D. Primary decontamination" }),
    rec({ n: 68, key: "68. 5.5.1 EMERG DECON 8",
      q: "A way that personnel, personal protective equipment, apparatus, and tools become contaminated is by:",
      c: ["working in the cold zone.", "working upwind and uphill from the hot zone.", "parking apparatus upwind.", "secondary contamination."], a: "D",
      r: ["5.5.1 (A-1, 2, 3), 5.3.1 (A-15, 17).", "pages 124, 479.", "pages 63, 126."],
      o: "68. A way that personnel, personal protective equipment, apparatus, and tools become contaminated is by: A. working in the cold zone. B. working upwind and uphill from the hot zone. C. parking apparatus upwind. D. secondary contamination." }),
    rec({ n: 69, key: "69. 5.6.1 PROG EVAL REP 6",
      q: "The hand signal with the responder placing their hands across the throat indicates:",
      c: ["vision problem.", "air problems.", "they are okay.", "hazardous atmosphere."], a: "B",
      notes: ["The question number is printed \"9.\" in the scan; it sits between questions 68 and 70 and matches key entry 69."],
      r: ["5.6.1 (A-3, 4, 5) (B-3, 4).", "page 464. Table 9.7.", "page 198. Fig. 8-12B."],
      o: "9. The hand signal with the responder placing their hands across the throat indicates: A. vision problem. B. air problems. C. they are okay. D. hazardous atmosphere." }),
    rec({ n: 70, key: "70. 6.2.1 PERS PROT EQUI 1",
      q: "To determine whether the personal protective equipment provided is appropriate for defensive operations, the Emergency Response Guidebook should be used. The section in which this information would be found is colored:",
      c: ["yellow.", "blue.", "orange.", "green."], a: "C",
      status: "needs_review",
      issues: [{ summary: "The Jones and Bartlett figure number is garbled.", excerpt: "3rd Ed, page 35-37, Fig 205", correction: "Confirm the figure number (the I-1 key prints Fig. 2-28 for this reference)." }],
      r: ["6.2.1 (A-1) (B-1), 5.3.1 (A-6, 14) (B-3).", "pages 118-119.", { t: "pages 35-37. Fig. [garbled, printed \"205\"].", x: true }],
      o: "70. To determine whether the personal protective equipment provided is appropriate for defensive operations, the Emergency Response Guidebook should be used. The section in which this information would be found is colored: A. yellow. B. biue. C. orange. D. green." }),
    rec({ n: 71, key: "71. 6.2.1 PERS PROT EQUI 9",
      q: "Work uniforms that provide minimal protection according to the Environmental Protection Agency is _____ protection.",
      c: ["Level A", "Level B", "Level C", "Level D"], a: "D",
      status: "needs_review", notes: ["The end of the stem is garbled in the scan (\"Agencyis_---- C-C#p rcotecttion\"); it was read as \"is _____ protection\", matching Examination II-2 question 6."],
      issues: [{ summary: "The end of the stem is garbled.", excerpt: "Environmental Protection Agencyis_---- C-C#p rcotecttion.", correction: "Confirm the stem wording against the printed page." }],
      r: ["6.2.1 (A-1, 3) (B-1).", "pages 443, 444, 447.", "page 194."],
      o: "71. Work uniforms that provide minimal protection according to the Environmental Protection Agencyis_---- C-C#p rcotecttion. A. Level A B. Level B C. Level C D. Level D" }),
    rec({ n: 72, key: "72. 6.2.1 PERS PROT EQUI 10",
      q: "The highest level of respiratory protection needed but lesser chemical protection required for the skin is:",
      c: ["Level A", "Level B", "Level C", "Level D"], a: "B",
      r: ["6.2.1 (A-1, 3) (B-1).", "pages 445-446.", "page 184."],
      o: "72. The highest level of respiratory protection needed but lesser chemical protection required for the skin is: A. Level A B. Level B C. Level C D. Level D" }),
    rec({ n: 73, key: "73. 6.2.1 PERS PROT EQUI 22",
      q: "Dizziness, headache, and nausea are all signs of:",
      c: ["heat stroke.", "heat cramps.", "heat exhaustion.", "heat failure."], a: "C",
      r: ["6.2.1 (A-3).", "page 455.", "page 142."],
      o: "73. Dizziness, headache, and nausea are all signs of: A. heat stroke. B. heat cramps. C. heat exhaustion. D. heat failure." }),
    rec({ n: 74, key: "74. 6.2.1 PERS PROT EQUI 24",
      q: "Penetration is the:",
      c: ["time for the chemical to move through the protective suit.", "physical damage from a chemical.", "occurring on a molecular level.", "movement of material through closures."], a: "D",
      r: ["6.2.1 (A-3).", "page 442. Fig. 9.26.", "pages 117, 180."],
      o: "74. Penetration is the: A. time for the chemical to move through the protective suit. B. physical damage from a chemical. C. occurring on a molecular level. D. movement of material through closures." }),
    rec({ n: 75, key: "75. 6.2.1 PERS PROT EQUI 26",
      q: "Symptoms of heat _____ include little or no sweating; hot, dry, red, skin; deep, then shallow breathing; and rapid pulse.",
      c: ["stroke", "exhaustion", "cramps", "rash"], a: "A",
      status: "needs_review", notes: [BLANK], issues: [blankIssue("75. Symptoms of heat include little or no sweating;")],
      r: ["6.2.1 (A-3).", "pages 455-456.", "page 142."],
      o: "75. Symptoms of heat include little or no sweating; hot, dry, red, skin; deep, then shallow breathing; and rapid pulse. A. stroke B. exhaustion C. cramps D. rash" })
  ];

  var meta = {
    id: "awareness-i2",
    sourceId: bank.sourceId,
    title: "Hazardous Materials Awareness — Examination I-2",
    shortLabel: "Examination I-2",
    level: "awareness",
    keyAppendix: "Appendix A",
    itemCount: 75,
    answerNote: "Answer letters and citations come from the Examination I-2 key in Appendix A. They have not been independently verified.",
    readingList: [
      "IFSTA, Hazardous Materials for First Responders, 5th Edition, Chapters 1–11 and 13.",
      "Jones and Bartlett Learning, Hazardous Materials Awareness and Operations, 3rd Ed, Chapters 1–2, 3–9, and 12."
    ],
    directions: "Examination I-2 has 75 items. The book says to remove it from the manual, take it in a quiet place without interruptions, and follow the Phase III time-management directions. Mark one answer, A–D, mark guesses, score the exam from the key, then review missed and guessed items.",
    sourceNotes: [
      "Key entries 9 and 36 have no answer line in the scan; both questions are held for review.",
      "Questions 3 and 20 depend on illustrations that are not in the scan."
    ]
  };

  bank.register(questions, meta);
})();
